import type { DockerContainerDetails, DockerContainerHealth, DockerContainerState, DockerContainerSummary, DockerMountDetails, DockerNetworkAttachmentDetails, DockerPortBindingSummary } from "./ContainerModels";
import { getDockerComposeMetadata } from "./DockerComposeMetadata";

type RawRecord = Record<string, unknown>;
const stateValues = new Set<DockerContainerState>(["created", "running", "paused", "restarting", "removing", "exited", "dead", "unknown"]);
const text = (value: unknown): string | undefined => typeof value === "string" && value.trim() ? value : undefined;
const object = (value: unknown): RawRecord => value && typeof value === "object" && !Array.isArray(value) ? value as RawRecord : {};
const array = (value: unknown): unknown[] => Array.isArray(value) ? value : [];

/** Converts unpredictable Docker Engine payloads into safe, presentation-ready models. */
export class ContainerMapper {
  static summary(raw: unknown, hostProfileId: string): DockerContainerSummary {
    const item = object(raw); const warnings: string[] = []; const names = array(item.Names).map(text).filter((value): value is string => Boolean(value)).map((name) => name.replace(/^\/+/, "")).filter(Boolean);
    const id = text(item.Id) ?? ""; if (!id) warnings.push("Container ID was missing.");
    const image = text(item.Image) ?? "Unknown image"; if (image === "Unknown image") warnings.push("Container image was missing.");
    const created = typeof item.Created === "number" && Number.isFinite(item.Created) ? item.Created : 0; if (!created) warnings.push("Container creation time was unavailable.");
    const state = this.state(item.State); if (state === "unknown") warnings.push("Container state was unrecognised.");
    const statusText = text(item.Status) ?? "Unknown status";
    const labels = strings(object(item.Labels));
    return { id, shortId: id ? id.slice(0, 12) : "Unknown ID", names, displayName: names[0] ?? "Unnamed container", image, imageId: text(item.ImageID), command: text(item.Command), createdAt: created ? new Date(created * 1000).toISOString() : "", createdTimestamp: created, state, statusText, health: this.healthFromStatus(statusText), exitCode: exitCode(statusText), ports: this.ports(item.Ports), mounts: this.mounts(item.Mounts), networks: this.networks(object(object(item.NetworkSettings).Networks)), labels, compose: getDockerComposeMetadata(labels), hostProfileId, mapperWarnings: warnings };
  }
  static details(raw: unknown): DockerContainerDetails {
    const item = object(raw); const config = object(item.Config); const state = object(item.State); const hostConfig = object(item.HostConfig); const networkSettings = object(item.NetworkSettings); const warnings: string[] = [];
    const environmentVariableNames = array(config.Env).map(text).filter((value): value is string => Boolean(value)).map((entry) => entry.split("=", 1)[0]).filter(Boolean);
    const mounts = this.mountDetails(item.Mounts); const networks = this.networkDetails(object(networkSettings.Networks)); const portBindings = this.portBindings(object(networkSettings.Ports));
    const healthRaw = object(state.Health); const healthLog = array(healthRaw.Log).slice(-5).map((entry) => { const result = object(entry); return { exitCode: number(result.ExitCode), output: bounded(text(result.Output), 500), startedAt: text(result.Start), endedAt: text(result.End) }; });
    return { id: text(item.Id) ?? "", name: (text(item.Name) ?? "Unnamed container").replace(/^\/+/, ""), image: text(config.Image) ?? "Unknown image", imageId: text(item.Image), createdAt: text(item.Created) ?? "", path: text(item.Path), args: array(item.Args).map(text).filter((value): value is string => Boolean(value)), command: text(config.Cmd), workingDirectory: text(config.WorkingDir), configuredUser: text(config.User), hostname: text(config.Hostname), domainName: text(config.Domainname), state: { status: this.state(state.Status), running: bool(state.Running), paused: bool(state.Paused), restarting: bool(state.Restarting), oomKilled: bool(state.OOMKilled), dead: bool(state.Dead), pid: number(state.Pid), exitCode: number(state.ExitCode), error: bounded(text(state.Error), 500), startedAt: text(state.StartedAt), finishedAt: text(state.FinishedAt), restartCount: number(item.RestartCount), health: Object.keys(healthRaw).length ? { status: this.health(text(healthRaw.Status)), failingStreak: number(healthRaw.FailingStreak), latestResults: healthLog } : undefined }, restartPolicy: text(object(hostConfig.RestartPolicy).Name) ? { name: text(object(hostConfig.RestartPolicy).Name)!, maximumRetryCount: number(object(hostConfig.RestartPolicy).MaximumRetryCount) } : undefined, mounts, networks, portBindings, exposedPorts: Object.keys(object(config.ExposedPorts)), labels: strings(object(config.Labels)), environmentVariableNames, entrypoint: array(config.Entrypoint).map(text).filter((value): value is string => Boolean(value)), stopSignal: text(config.StopSignal), stopTimeout: number(config.StopTimeout), tty: bool(config.Tty), openStdin: bool(config.OpenStdin), readOnlyRootFilesystem: bool(hostConfig.ReadonlyRootfs), privileged: bool(hostConfig.Privileged), capAdd: array(hostConfig.CapAdd).map(text).filter((value): value is string => Boolean(value)), capDrop: array(hostConfig.CapDrop).map(text).filter((value): value is string => Boolean(value)), mapperWarnings: warnings };
  }
  static state(value: unknown): DockerContainerState { const normalized = text(value)?.toLowerCase() ?? "unknown"; return stateValues.has(normalized as DockerContainerState) ? normalized as DockerContainerState : "unknown"; }
  static health(value: unknown): DockerContainerHealth { const normalized = text(value)?.toLowerCase(); return normalized === "healthy" || normalized === "unhealthy" || normalized === "starting" ? normalized : normalized ? "unknown" : "none"; }
  private static healthFromStatus(status: string): DockerContainerHealth { const match = /\((healthy|unhealthy|health: starting|starting)\)/i.exec(status); return match ? this.health(match[1].replace("health: ", "")) : "none"; }
  private static ports(value: unknown) { const seen = new Set<string>(); return array(value).flatMap((port) => { const item = object(port); const privatePort = number(item.PrivatePort); const publicPort = number(item.PublicPort); const protocol = text(item.Type)?.toLowerCase() ?? "tcp"; const ip = text(item.IP); const key = `${privatePort ?? ""}:${publicPort ?? ""}:${protocol}:${ip ?? ""}`; if (seen.has(key) || privatePort === undefined) return []; seen.add(key); return [{ privatePort, publicPort, protocol, ip, type: publicPort === undefined ? "exposed" as const : "published" as const }]; }); }
  private static mounts(value: unknown) { return array(value).map((mount) => { const item = object(mount); return { type: text(item.Type) ?? "unknown", source: text(item.Source), destination: text(item.Destination) ?? "Unknown destination", readOnly: bool(item.RW) === false ? true : undefined, name: text(item.Name) }; }); }
  private static networks(value: RawRecord) { return Object.keys(value).sort(natural).map((name) => ({ name })); }
  private static mountDetails(value: unknown): DockerMountDetails[] { return array(value).map((mount) => { const item = object(mount); return { type: text(item.Type) ?? "unknown", source: text(item.Source), destination: text(item.Destination) ?? "Unknown destination", readOnly: bool(item.RW) === false ? true : undefined, name: text(item.Name), driver: text(item.Driver), propagation: text(item.Propagation) }; }); }
  private static networkDetails(value: RawRecord): DockerNetworkAttachmentDetails[] { return Object.keys(value).sort(natural).map((name) => { const item = object(value[name]); return { name, ipAddress: text(item.IPAddress), globalIPv6Address: text(item.GlobalIPv6Address), gateway: text(item.Gateway), macAddress: text(item.MacAddress), aliases: array(item.Aliases).map(text).filter((value): value is string => Boolean(value)) }; }); }
  private static portBindings(value: RawRecord): DockerPortBindingSummary[] { return Object.keys(value).sort(natural).map((containerPort) => ({ containerPort, bindings: array(value[containerPort]).map((binding) => { const item = object(binding); return { hostIp: text(item.HostIp), hostPort: text(item.HostPort) }; }) })); }
}
function strings(value: RawRecord): Record<string, string> { return Object.fromEntries(Object.entries(value).filter((entry): entry is [string, string] => typeof entry[1] === "string")); }
function number(value: unknown): number | undefined { return typeof value === "number" && Number.isFinite(value) ? value : undefined; }
function bool(value: unknown): boolean | undefined { return typeof value === "boolean" ? value : undefined; }
function exitCode(status: string): number | undefined { const match = /Exited \((-?\d+)\)/i.exec(status); return match ? Number(match[1]) : undefined; }
function bounded(value: string | undefined, length: number): string | undefined { return value && value.length > length ? `${value.slice(0, length)}…` : value; }
function natural(a: string, b: string): number { return a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" }); }
