import type { ContainerSortMode, ContainersViewState, DockerContainerSummary } from "./ContainerModels";

/** Pure client-side filtering and stable ordering for [[Docker Connector - Container Filters and Sorting]]. */
export function selectContainers(containers: DockerContainerSummary[], state: ContainersViewState, availableUpdateKeys: ReadonlySet<string> = new Set()): DockerContainerSummary[] { return stableSort(containers.filter((container) => matchesSearch(container, state.searchQuery) && matchesState(container, state.stateFilter) && (state.healthFilter === "all" || container.health === state.healthFilter) && (!state.networkFilter || container.networks.some((network) => network.name === state.networkFilter)) && (!state.updatesOnly || availableUpdateKeys.has(updateKey(container.hostProfileId, container.id)))), state.sortMode); }
export function matchesSearch(container: DockerContainerSummary, query: string): boolean { const needle = query.trim().toLocaleLowerCase(); if (!needle) return true; return searchableValues(container).some((value) => value.toLocaleLowerCase().includes(needle)); }
export function matchesState(container: DockerContainerSummary, filter: ContainersViewState["stateFilter"]): boolean { return filter === "all" || (filter === "stopped" ? ["exited", "dead", "created"].includes(container.state) : container.state === filter); }
export function uniqueNetworks(containers: DockerContainerSummary[]): string[] { return [...new Set(containers.flatMap((container) => container.networks.map((network) => network.name)))].sort(natural); }
export function activeFilterLabels(state: ContainersViewState): Array<{ id: "search" | "state" | "health" | "network" | "updates"; label: string }> { const filters: Array<{ id: "search" | "state" | "health" | "network" | "updates"; label: string }> = [{ id: "search", label: state.searchQuery ? `Search: ${state.searchQuery}` : "" }, { id: "state", label: state.stateFilter !== "all" ? title(state.stateFilter) : "" }, { id: "health", label: state.healthFilter !== "all" ? title(state.healthFilter) : "" }, { id: "network", label: state.networkFilter ? `Network: ${state.networkFilter}` : "" }, { id: "updates", label: state.updatesOnly ? "Updates available" : "" }]; return filters.filter((item) => Boolean(item.label)); }
export function updateKey(profileId: string, containerId: string): string { return `${profileId}:${containerId}`; }
export function resultCountText(resultCount: number, total: number): string { const noun = total === 1 ? "container" : "containers"; return resultCount === total ? `${total} ${noun}` : `${resultCount} of ${total} ${noun}`; }
export function searchableValues(container: DockerContainerSummary): string[] { return [container.displayName, ...container.names, container.id, container.shortId, container.image, container.state, container.statusText, container.health, ...container.ports.flatMap((port) => [String(port.privatePort ?? ""), String(port.publicPort ?? ""), port.protocol, port.ip ?? ""]), ...container.networks.map((network) => network.name), ...container.mounts.flatMap((mount) => [mount.source ?? "", mount.destination]), ...Object.entries(container.labels).flatMap(([key, value]) => [key, value])]; }
function stableSort(containers: DockerContainerSummary[], mode: ContainerSortMode): DockerContainerSummary[] { return containers.map((container, index) => ({ container, index })).sort((a, b) => compare(a.container, b.container, mode) || natural(a.container.displayName, b.container.displayName) || natural(a.container.id, b.container.id) || a.index - b.index).map(({ container }) => container); }
function compare(a: DockerContainerSummary, b: DockerContainerSummary, mode: ContainerSortMode): number { switch (mode) { case "name-asc": return natural(a.displayName, b.displayName); case "name-desc": return natural(b.displayName, a.displayName); case "state": return natural(a.state, b.state); case "health": return natural(a.health, b.health); case "created-newest": return missingLast(b.createdTimestamp, a.createdTimestamp); case "created-oldest": return missingLast(a.createdTimestamp, b.createdTimestamp); case "image-asc": return natural(a.image, b.image); case "uptime-longest": return a.state === "running" && b.state === "running" ? a.createdTimestamp - b.createdTimestamp : Number(b.state === "running") - Number(a.state === "running"); case "uptime-shortest": return a.state === "running" && b.state === "running" ? b.createdTimestamp - a.createdTimestamp : Number(b.state === "running") - Number(a.state === "running"); case "restart-highest": return missingLast(b.restartCount, a.restartCount); case "restart-lowest": return missingLast(a.restartCount, b.restartCount); } }
function missingLast(a: number | undefined, b: number | undefined): number { if (a === undefined) return b === undefined ? 0 : 1; if (b === undefined) return -1; return a - b; }
function natural(a: string, b: string): number { return a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" }); }
function title(value: string): string { return value.replace(/-/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
