import { Modal, Notice, setIcon } from "obsidian";
import type DockerConnectorPlugin from "../main";
import type { DockerConnectionProfile } from "../models/DockerConnectionProfile";
import type { DockerContainerSummary } from "./ContainerModels";
import type { ContainerUpdatePreview } from "../services/ContainerUpdatePlan";
import type { ContainerUpdateProgressEvent, ContainerUpdateResult } from "../services/DockerContainerActionService";

type ContainerUpdateDialogPhase = "loading-preflight" | "awaiting-confirmation" | "updating" | "rolling-back" | "completed" | "failed" | "cancelled";
const STAGES = ["inspecting", "validating", "pulling-image", "comparing-images", "stopping-original", "creating-backup", "creating-replacement", "connecting-networks", "starting-replacement", "verifying", "removing-backup", "completed"] as const;
const LABELS: Record<string, string> = { inspecting: "Inspecting container", validating: "Validating configuration", "pulling-image": "Pulling image", "comparing-images": "Comparing image versions", "stopping-original": "Stopping original container", "creating-backup": "Creating rollback backup", "creating-replacement": "Creating replacement container", "connecting-networks": "Restoring network connections", "starting-replacement": "Starting replacement container", verifying: "Verifying replacement", "removing-backup": "Removing rollback backup", completed: "Update complete", "rolling-back": "Restoring original container" };

/** Safe UI shell: read-only preflight first, then delegates all mutation to DockerContainerActionService. */
export class ContainerUpdateDialog extends Modal {
  private phase: ContainerUpdateDialogPhase = "loading-preflight";
  private preview?: ContainerUpdatePreview;
  private error?: { code?: string; message: string };
  private startedAt?: number;
  private events = new Map<string, ContainerUpdateProgressEvent>();
  private removeProgress?: () => void;
  private finished = false;
  private readonly attemptId = crypto.randomUUID();

  constructor(private readonly plugin: DockerConnectorPlugin, private readonly profile: DockerConnectionProfile, private readonly container: DockerContainerSummary, private readonly onUpdated: (newId?: string) => void) { super(plugin.app); }
  onOpen(): void { this.modalEl.addClasses(["dc-resizable-modal", "dc-update-dialog"]); void this.loadPreflight(); }
  onClose(): void { this.removeProgress?.(); this.contentEl.empty(); }

  private async loadPreflight(): Promise<void> { this.phase = "loading-preflight"; this.error = undefined; this.render(); try { this.preview = await this.plugin.preflightContainerUpdate(this.profile, this.container.id); this.phase = "awaiting-confirmation"; } catch (error) { this.phase = "failed"; this.error = safeError(error); } this.render(); }
  private render(): void { const root = this.contentEl; root.empty(); root.createEl("h2", { text: this.phase === "failed" ? "Update unavailable" : "Update container" }); const body = root.createDiv({ cls: "dc-update-dialog__body" }); if (this.phase === "loading-preflight") { body.createDiv({ text: "Preparing update information…", cls: "dc-update-dialog-live", attr: { "aria-live": "polite" } }); return; } if (this.phase === "failed") { body.createDiv({ text: this.error?.message ?? "The update could not be prepared.", cls: "dc-update-dialog-result is-failed", attr: { role: "alert" } }); if (this.error?.code) body.createDiv({ text: this.error.code, cls: "docker-connector__muted" }); this.footer(body, [["Retry check", () => void this.loadPreflight()], ["Close", () => this.close()]]); return; }
    if (this.phase === "awaiting-confirmation") { this.previewView(body); return; }
    if (this.phase === "updating" || this.phase === "rolling-back") { this.progressView(body); return; }
    this.resultView(body);
  }
  private previewView(root: HTMLElement): void { const preview = this.preview!; root.createDiv({ text: "Review the image and configuration before proceeding.", cls: "docker-connector__muted" }); const summary = root.createDiv({ cls: "dc-update-dialog-summary" }); this.rows(summary, [["Container", preview.containerName], ["Docker host", this.profile.name], ["Connection", connectionLabel(this.profile)], ["Current state", preview.wasRunning ? "Running" : "Stopped"], ["Image", preview.imageReference], ["Current image ID", short(preview.currentImageId)], ["Available update", "The configured image will be pulled before the container is recreated."], ["Pull source", `${repository(preview.imageReference)} · ${tag(preview.imageReference)}`]]); root.createEl("h3", { text: "Configuration to preserve" }); this.rows(root, [["Named volumes", String(preview.namedVolumeCount)], ["Bind mounts", String(preview.bindMountCount)], ["Published ports", String(preview.publishedPortCount)], ["Networks", String(preview.networkNames.length)], ["Environment variables", String(preview.environmentCount)], ["Labels", String(preview.labelCount)], ["Restart policy", preview.restartPolicy ?? "Default"], ["Health check", preview.healthcheck ? "Present" : "None"], ["Working directory", preview.workingDirectory], ["Configured user", preview.configuredUser], ["Stop timeout", `${preview.stopTimeout} seconds`], ["Read-only root filesystem", preview.readOnlyRootFilesystem === undefined ? undefined : preview.readOnlyRootFilesystem ? "Yes" : "No"]]); const networks = root.createEl("details"); networks.createEl("summary", { text: `Networks (${preview.networkNames.length})` }); preview.networkNames.forEach((name) => networks.createDiv({ text: name })); const warning = root.createDiv({ cls: "dc-update-dialog-warning", attr: { role: "note" } }); warning.createEl("strong", { text: "Service interruption and data warning" }); warning.createDiv({ text: "The container will be recreated. Named volumes and bind mounts will be preserved, but data stored only in the writable layer may be lost. The old image is not deleted." }); this.footer(root, [["Cancel", () => this.close()], ["Proceed with update", () => void this.proceed()]]); }
  private progressView(root: HTMLElement): void { const rollingBack = this.phase === "rolling-back"; root.createDiv({ text: rollingBack ? "Update failed. Restoring original container…" : `Updating ${this.container.displayName}`, cls: "dc-update-dialog-live", attr: { "aria-live": rollingBack ? "assertive" : "polite" } }); root.createDiv({ text: `Docker host: ${this.profile.name} · Image: ${this.preview?.imageReference ?? this.container.image} · Elapsed: ${elapsed(this.startedAt)}`, cls: "docker-connector__muted" }); const list = root.createDiv({ cls: "dc-update-dialog-steps" }); const stages = rollingBack ? ["rolling-back"] : STAGES; stages.forEach((stage) => { const event = this.events.get(stage); const row = list.createDiv({ cls: `is-${event?.state ?? "pending"}` }); const icon = row.createSpan({ attr: { "aria-hidden": "true" } }); setIcon(icon, event?.state === "complete" ? "check" : event?.state === "warning" ? "triangle-alert" : event?.state === "failed" ? "circle-x" : event?.state === "running" ? "loader-circle" : "circle" ); row.createSpan({ text: `${LABELS[stage]} — ${event?.state ?? "Pending"}` }); }); if (!rollingBack) this.footer([["Cancel and restore original", () => this.plugin.containerActions.cancelUpdate(this.profile.id, this.container.id)]]); }
  private async proceed(): Promise<void> { if (!this.preview) return; this.phase = "updating"; this.startedAt = Date.now(); this.removeProgress = this.plugin.onContainerUpdateProgress((event) => { if (event.attemptId !== this.attemptId || event.profileId !== this.profile.id || event.containerId !== this.container.id || this.finished) return; this.events.set(event.stage, event); if (event.stage === "rolling-back") this.phase = "rolling-back"; this.render(); }); this.render(); const result = await this.plugin.updateContainer(this.profile, this.container.id, true, this.attemptId); this.finished = true; this.removeProgress?.(); this.phase = result.status === "cancelled" ? "cancelled" : result.status === "failed-before-mutation" || result.status === "failed-rolled-back" || result.status === "failed-rollback-incomplete" ? "failed" : "completed"; this.error = failureSummary(result); this.result = result; this.render(); this.notice(result); }
  private result?: ContainerUpdateResult;
  private resultView(root: HTMLElement): void { const result = this.result; const title = result?.status === "updated" ? "Update complete" : result?.status === "updated-with-backup-retained" ? "Update completed with a warning" : result?.status === "already-current" ? "No update needed" : result?.status === "cancelled" ? "Update cancelled" : "Update failed"; root.createDiv({ text: title, cls: `dc-update-dialog-result is-${this.phase}`, attr: { role: this.phase === "failed" ? "alert" : "status" } }); if (this.error) { root.createDiv({ text: this.error.message }); if (this.error.code) root.createDiv({ text: this.error.code, cls: "docker-connector__muted" }); } if (result?.status === "updated" || result?.status === "updated-with-backup-retained") this.rows(root, [["Previous image", short(result.oldImageId)], ["New image", short(result.newImageId)], ["Replacement container", short(result.newContainerId)], ...(result.status === "updated-with-backup-retained" ? [["Backup retained", result.backupContainerName] as [string, string]] : [])]); if (result?.status === "already-current") this.rows(root, [["Image", this.preview?.imageReference], ["Image ID", short(result.imageId)]]); this.footer([["Close", () => this.close()], ...(result?.status === "updated" || result?.status === "updated-with-backup-retained" ? [["Open updated container", () => { this.onUpdated(result.newContainerId); this.close(); }] as [string, () => void]] : result?.status === "failed-rolled-back" || result?.status === "failed-before-mutation" ? [["Retry update", () => void this.loadPreflight()] as [string, () => void]] : [])]); }
  private rows(root: HTMLElement, rows: Array<[string, string | undefined]>): void { const grid = root.createDiv({ cls: "dc-update-dialog-summary" }); rows.filter(([, value]) => Boolean(value)).forEach(([label, value]) => { const row = grid.createDiv(); row.createSpan({ text: label }); row.createSpan({ text: value! }); }); }
  private footer(_bodyOrActions: HTMLElement | Array<[string, () => void, boolean?]>, maybeActions?: Array<[string, () => void, boolean?]>): void { const actions = maybeActions ?? _bodyOrActions as Array<[string, () => void, boolean?]>; const footer = this.contentEl.createDiv({ cls: "dc-update-dialog-footer" }); actions.forEach(([label, action, disabled]) => { const button = footer.createEl("button", { text: label, cls: label.startsWith("Proceed") ? "mod-cta" : "" }); button.disabled = Boolean(disabled); button.onclick = action; }); }
  private notice(result: ContainerUpdateResult): void { const name = this.container.displayName; new Notice(result.status === "updated" ? `Container update completed: ${name}` : result.status === "already-current" ? `Container already uses the current image: ${name}` : result.status === "failed-rolled-back" ? `Container update failed; original restored: ${name}` : result.status === "failed-rollback-incomplete" ? `Container update requires manual recovery: ${name}` : "Container update finished."); }
}
function safeError(error: unknown): { code?: string; message: string } { return error && typeof error === "object" && "code" in error && "message" in error ? { code: String((error as { code: unknown }).code), message: String((error as { message: unknown }).message).slice(0, 240) } : { message: error instanceof Error ? error.message.slice(0, 240) : "The update preflight could not be completed." }; }
function failureSummary(result: ContainerUpdateResult): { code?: string; message: string } | undefined { if (result.status === "failed-rolled-back") return { code: result.errorCode, message: "Update failed — original restored." }; if (result.status === "failed-rollback-incomplete") return { code: result.errorCode, message: result.safeRecoveryInstructions }; if (result.status === "failed-before-mutation") return { code: result.errorCode, message: "The original container was not changed." }; return undefined; }
function short(value: string | undefined): string | undefined { return value ? value.replace(/^sha256:/, "").slice(0, 12) : undefined; }
function repository(image: string): string { return image.slice(0, image.lastIndexOf(":")); }
function tag(image: string): string { return image.slice(image.lastIndexOf(":") + 1); }
function elapsed(startedAt: number | undefined): string { return startedAt ? `${Math.max(0, Math.floor((Date.now() - startedAt) / 1000))}s` : "0s"; }
function connectionLabel(profile: DockerConnectionProfile): string { return profile.connectionType === "docker-tls" ? "Remote Docker API (Mutual TLS)" : profile.connectionType === "docker-context" ? "Docker Context" : profile.connectionType === "local" ? "Local Docker Socket" : "Remote Docker via SSH"; }
