services:
  docker-connector-gateway:
    build: .
    read_only: true
    tmpfs: ["/tmp"]
    security_opt: ["no-new-privileges:true"]
    cap_drop: ["ALL"]
    environment:
      GATEWAY_TOKEN: "replace-with-a-32+-character-random-token"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "127.0.0.1:8787:8787"
