import * as https from "node:https";
import { isIP } from "node:net";
import { readFile } from "node:fs/promises";
import type { DockerTlsProfile } from "../models/DockerConnectionProfile";
import { validateDockerTlsFiles } from "../security/TlsProfileValidation";
import { dockerHttpError, DockerConnectionError, type ConnectionTestStep, type DockerApiRequest, type DockerConnectionTestResult, type DockerTransport } from "./DockerTransport";

const TIMEOUT = 20_000, MAX_BODY = 16 * 1024 * 1024;
/**
 * Native HTTPS Docker transport with mandatory CA, client certificate, and
 * hostname verification. Insecure TCP is intentionally unsupported: both the
 * persistent agent and each request set rejectUnauthorized: true. Loaded PEM
 * buffers are cleared when the transport disconnects and are never persisted.
 */
export class DockerMutualTlsTransport implements DockerTransport {
  private agent?: https.Agent; private connected = false; private material?: { ca: Buffer; cert: Buffer; key: Buffer };
  constructor(readonly profile: DockerTlsProfile, private readonly passphrase: () => string | undefined = () => undefined) {}
  async connect(): Promise<void> { if (this.connected) return; await validateDockerTlsFiles({ caCertificatePath: this.profile.caCertificatePath, clientCertificatePath: this.profile.clientCertificatePath, clientKeyPath: this.profile.clientKeyPath, clientKeyPassphrase: this.passphrase() }); try { this.material = { ca: await readFile(this.profile.caCertificatePath), cert: await readFile(this.profile.clientCertificatePath), key: await readFile(this.profile.clientKeyPath) }; const servername = tlsServername(this.profile.serverName); this.agent = new https.Agent({ keepAlive: true, maxSockets: 2, ca: this.material.ca, cert: this.material.cert, key: this.material.key, passphrase: this.passphrase(), ...(servername ? { servername } : {}), rejectUnauthorized: true }); this.connected = true; } catch (error) { await this.disconnect(); throw error; } }
  isConnected(): boolean { return this.connected; }
  async disconnect(): Promise<void> { this.connected = false; this.agent?.destroy(); this.agent = undefined; this.material?.ca.fill(0); this.material?.cert.fill(0); this.material?.key.fill(0); this.material = undefined; }
  async request<T>(request: DockerApiRequest): Promise<T> { const body = await this.raw(request.path, request.method, request.body); if (request.responseType === "empty") return undefined as T; if (request.responseType === "text") return body as T; try { return JSON.parse(body) as T; } catch { throw new DockerConnectionError("DOCKER_RESPONSE_INVALID", "Docker returned an invalid JSON response."); } }
  async testConnection(): Promise<DockerConnectionTestResult> { const steps: ConnectionTestStep[] = ["Validate profile", "Load TLS certificates", "Verify certificate and key match", "Create mutual-TLS transport", "Open TLS connection", "Verify server certificate", "Verify server name", "Send Docker GET /_ping", "Receive Docker ping response", "Send Docker GET /version", "Receive Docker version response", "Parse Docker response"].map((label, index) => ({ id: `tls-${index}`, label, status: "pending" })); try { steps[0].status = "success"; steps[1].status = "running"; await this.connect(); steps[1].status = "success"; steps[2].status = "success"; steps[3].status = "success"; steps[7].status = "running"; const ping = await this.raw("/_ping"); if (ping.trim() !== "OK") throw new DockerConnectionError("DOCKER_PING_FAILED", "Docker /_ping returned an unexpected response."); [4, 5, 6, 7, 8].forEach((index) => steps[index].status = "success"); steps[9].status = "running"; const version = JSON.parse(await this.raw("/version")) as { Version?: string; ApiVersion?: string }; if (!version.Version || !version.ApiVersion) throw new DockerConnectionError("DOCKER_RESPONSE_INVALID", "Docker /version response was incomplete."); steps[9].status = "success"; steps[10].status = "success"; steps[11].status = "success"; return { success: true, steps, dockerVersion: version.Version, apiVersion: version.ApiVersion }; } catch (error) { const typed = error instanceof DockerConnectionError ? error : mapTlsError(error); const failure = tlsDiagnosticFailureStep(typed.code); if (failure === 6) [4, 5].forEach((index) => steps[index].status = "success"); steps[failure].status = "error"; steps.filter((step) => step.status === "pending" || step.status === "running").forEach((step) => { if (step !== steps[failure]) step.status = "skipped"; }); return { success: false, steps, safeErrorCode: typed.code, safeErrorMessage: typed.message }; } finally { await this.disconnect(); } }
  private async raw(path: string, method: DockerApiRequest["method"] = "GET", body?: string): Promise<string> { if (!this.connected) await this.connect(); const servername = tlsServername(this.profile.serverName); return new Promise((resolve, reject) => { let timer: number | undefined; const request = https.request({ host: this.profile.host, port: this.profile.port, ...(servername ? { servername } : {}), method, path, ca: this.material?.ca, cert: this.material?.cert, key: this.material?.key, passphrase: this.passphrase(), rejectUnauthorized: true, agent: this.agent, headers: { Host: this.profile.serverName, Connection: "keep-alive", ...(body ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body) } : {}) } }, (response) => { const chunks: Buffer[] = []; let length = 0; response.on("data", (chunk: Buffer) => { length += chunk.length; if (length > MAX_BODY) request.destroy(new DockerConnectionError("DOCKER_HTTP_FAILED", "Docker response exceeded the safe size limit.")); else chunks.push(chunk); }); response.once("end", () => { if (timer) window.clearTimeout(timer); const responseBody = Buffer.concat(chunks).toString("utf8"); const status = response.statusCode ?? 0; if (status < 200 || status >= 300) reject(dockerHttpError(status, responseBody, path === "/_ping")); else resolve(responseBody); }); }); timer = window.setTimeout(() => request.destroy(new DockerConnectionError("DOCKER_TLS_REQUEST_TIMEOUT", "Docker TLS endpoint did not respond in time.")), dockerRequestTimeout(path)); request.once("error", (error) => { if (timer) window.clearTimeout(timer); reject(mapTlsError(error)); }); request.end(body); }); }
}
/** Docker holds a stop request open until the selected grace period expires. */
export function dockerRequestTimeout(path: string): number { const match = /^\/containers\/[a-f0-9]{12,64}\/stop\?t=(\d+)$/.exec(path); return match ? Math.max(TIMEOUT, (Number(match[1]) + 10) * 1_000) : TIMEOUT; }
export function tlsServername(certificateIdentity: string): string | undefined { return isIP(certificateIdentity) ? undefined : certificateIdentity; }
export function tlsDiagnosticFailureStep(code: string): number { return code === "DOCKER_TLS_HOSTNAME_MISMATCH" ? 6 : code === "DOCKER_TLS_CA_UNTRUSTED" || code === "DOCKER_TLS_SERVER_CERT_EXPIRED" ? 5 : code.startsWith("DOCKER_TLS_") ? 4 : code === "DOCKER_PING_FAILED" ? 8 : 11; }
function mapTlsError(error: unknown): DockerConnectionError { const code = error && typeof error === "object" ? (error as NodeJS.ErrnoException).code : undefined; if (code === "ERR_TLS_CERT_ALTNAME_INVALID") return new DockerConnectionError("DOCKER_TLS_HOSTNAME_MISMATCH", "The Docker server certificate does not match the configured Server Name."); if (["UNABLE_TO_VERIFY_LEAF_SIGNATURE", "UNABLE_TO_GET_ISSUER_CERT", "UNABLE_TO_GET_ISSUER_CERT_LOCALLY", "SELF_SIGNED_CERT_IN_CHAIN"].includes(String(code))) return new DockerConnectionError("DOCKER_TLS_CA_UNTRUSTED", "The Docker server certificate could not be verified with the selected CA certificate."); if (code === "CERT_HAS_EXPIRED") return new DockerConnectionError("DOCKER_TLS_SERVER_CERT_EXPIRED", "The Docker server certificate has expired."); if (code === "ENOTFOUND" || code === "EAI_AGAIN") return new DockerConnectionError("DOCKER_TLS_DNS_FAILED", "Docker TLS host name could not be resolved."); if (code === "ECONNREFUSED") return new DockerConnectionError("DOCKER_TLS_CONNECTION_REFUSED", "The Docker TLS endpoint refused the connection. Confirm Docker Engine is running and listening on the configured TLS port."); if (code === "ECONNRESET") return new DockerConnectionError("DOCKER_TLS_CONNECTION_RESET", "The Docker TLS connection was reset."); return new DockerConnectionError("DOCKER_TLS_HANDSHAKE_FAILED", "Docker mutual-TLS connection failed."); }
