import * as http from "node:http";
import type { LocalDockerProfile } from "../models/DockerConnectionProfile";
import { validateUnixSocket, normalizeLocalEndpoint, type LocalDockerEndpoint } from "./LocalEndpointDiscovery";
import { dockerHttpError, DockerConnectionError, type ConnectionTestStep, type DockerApiRequest, type DockerConnectionTestResult, type DockerTransport } from "./DockerTransport";

/**
 * Local Docker transport
 *
 * Talks directly to a user-selected Unix socket or Windows named pipe.  This
 * is intentionally not a TCP transport: insecure Docker TCP endpoints are
 * unsupported.  Requests still pass through the shared Docker API policy, and
 * the bounded body and timeout handling prevent an unhealthy local daemon from
 * retaining plugin resources indefinitely.
 */
const TIMEOUT = 20_000, MAX_BODY = 16 * 1024 * 1024;
export class LocalDockerTransport implements DockerTransport {
  private connected = false; private endpoint?: LocalDockerEndpoint; private readonly agent = new http.Agent({ keepAlive: true, maxSockets: 4 });
  constructor(readonly profile: LocalDockerProfile) {}
  async connect(): Promise<void> { this.endpoint = this.profile.localEndpoint.type === "unix-socket" ? await validateUnixSocket(this.profile.localEndpoint) : normalizeLocalEndpoint(this.profile.localEndpoint); this.connected = true; }
  isConnected(): boolean { return this.connected; }
  async disconnect(): Promise<void> { this.connected = false; this.agent.destroy(); }
  async request<T>(request: DockerApiRequest): Promise<T> { const body = await this.raw(request.path, request.method, request.body); if (request.responseType === "empty") return undefined as T; if (request.responseType === "text") return body as T; try { return JSON.parse(body) as T; } catch { throw new DockerConnectionError("DOCKER_RESPONSE_INVALID", "The local endpoint responded, but the response was not valid Docker JSON."); } }
  async testConnection(): Promise<DockerConnectionTestResult> { const steps: ConnectionTestStep[] = ["Validate profile", "Validate local endpoint", "Send Docker GET /_ping", "Receive Docker ping response", "Send Docker GET /version", "Receive Docker version response", "Parse Docker response"].map((label, index) => ({ id: `local-${index}`, label, status: "pending" })); try { steps[0].status = "success"; await this.connect(); steps[1].status = "success"; steps[2].status = "success"; const ping = await this.raw("/_ping"); if (ping.trim() !== "OK") throw new DockerConnectionError("DOCKER_PING_FAILED", "Docker /_ping returned an unexpected response."); steps[3].status = "success"; steps[4].status = "success"; const body = await this.raw("/version"); const version = JSON.parse(body) as { Version?: string; ApiVersion?: string }; if (!version.Version || !version.ApiVersion) throw new DockerConnectionError("DOCKER_RESPONSE_INVALID", "Docker /version response was incomplete."); steps[5].status = "success"; steps[6].status = "success"; return { success: true, steps, dockerVersion: version.Version, apiVersion: version.ApiVersion }; } catch (error) { const active = [...steps].reverse().find((step) => step.status === "pending" || step.status === "success"); if (active) active.status = "error"; steps.filter((step) => step.status === "pending").forEach((step) => step.status = "skipped"); const typed = error instanceof DockerConnectionError ? error : mapLocalError(error); return { success: false, steps, safeErrorCode: typed.code, safeErrorMessage: typed.message }; } finally { await this.disconnect(); } }
  private async raw(path: string, method: DockerApiRequest["method"] = "GET", body?: string): Promise<string> { if (!this.connected) await this.connect(); const endpoint = this.endpoint!; return new Promise((resolve, reject) => { let timer: ReturnType<typeof setTimeout> | undefined; const options: http.RequestOptions = { method, path, headers: { Host: "docker", Connection: "keep-alive", ...(body ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(body) } : {}) }, agent: this.agent, ...(endpoint.type === "unix-socket" ? { socketPath: endpoint.socketPath } : { socketPath: endpoint.pipePath }) }; const request = http.request(options, (response) => { const chunks: Buffer[] = []; let length = 0; response.on("data", (chunk: Buffer) => { length += chunk.length; if (length > MAX_BODY) { request.destroy(); reject(new DockerConnectionError("DOCKER_HTTP_FAILED", "Docker response exceeded the safe size limit.")); } else chunks.push(chunk); }); response.once("end", () => { if (timer) clearTimeout(timer); const responseBody = Buffer.concat(chunks).toString("utf8"); const status = response.statusCode ?? 0; if (status < 200 || status >= 300) { reject(dockerHttpError(status, responseBody, path === "/_ping")); return; } resolve(responseBody); }); response.once("error", (error) => reject(mapLocalError(error))); }); timer = setTimeout(() => { request.destroy(); reject(new DockerConnectionError("LOCAL_SOCKET_TIMEOUT", "The local Docker endpoint did not respond in time.")); }, TIMEOUT); request.once("error", (error) => { if (timer) clearTimeout(timer); reject(mapLocalError(error)); }); request.end(body); }); }
}
function mapLocalError(error: unknown, pipe = false): DockerConnectionError { const code = error && typeof error === "object" ? (error as NodeJS.ErrnoException).code : undefined; if (typeof code === "string" && code.startsWith("LOCAL_")) return new DockerConnectionError(code, error instanceof Error ? error.message : "The local Docker endpoint could not be opened."); const prefix = pipe ? "LOCAL_PIPE" : "LOCAL_SOCKET"; if (code === "ENOENT") return new DockerConnectionError(`${prefix}_NOT_FOUND`, pipe ? "The Docker named pipe could not be opened. Confirm Docker Desktop or Docker Engine is running." : "Docker socket not found. Docker may not be running, or it may use a different socket."); if (code === "EACCES" || code === "EPERM") return new DockerConnectionError(`${prefix}_PERMISSION_DENIED`, pipe ? "Obsidian cannot access the Docker named pipe." : "Obsidian cannot access the local Docker socket."); if (code === "EBUSY") return new DockerConnectionError("LOCAL_PIPE_BUSY", "The Docker named pipe is busy. Retry after the current operation completes."); if (code === "ECONNREFUSED") return new DockerConnectionError(`${prefix}_CONNECTION_REFUSED`, "The local Docker endpoint was found, but the Docker daemon refused the connection."); if (code === "ECONNRESET") return new DockerConnectionError(`${prefix}_CONNECTION_RESET`, "The local Docker connection was reset before the request completed."); if (code === "EPIPE") return new DockerConnectionError(`${prefix}_CLOSED`, "The local Docker connection closed before the request completed."); if (code === "ETIMEDOUT") return new DockerConnectionError(`${prefix}_TIMEOUT`, "The local Docker daemon did not respond before the timeout."); return new DockerConnectionError(`${prefix}_CONNECTION_FAILED`, "The local Docker endpoint could not be opened."); }
