import { lstat, realpath, stat } from "node:fs/promises";
import { homedir } from "node:os";
import { normalize, resolve } from "node:path";

/**
 * Local Docker endpoint discovery
 *
 * Finds a small, explicit set of conventional Docker socket locations.  It
 * never recursively scans the filesystem and it does not silently choose one
 * endpoint when several are available.  A configured path is normalised and
 * validated as a socket before it reaches the local transport.
 */
export type LocalDockerEndpoint = { type: "unix-socket"; socketPath: string } | { type: "windows-named-pipe"; pipePath: string };
export interface ResolvedUnixSocket { configuredPath: string; expandedPath: string; resolvedPath: string; exists: boolean; isSymbolicLink: boolean; linkTarget?: string; targetExists: boolean; isSocket: boolean; }
export interface LocalEndpointCandidate { id: string; type: LocalDockerEndpoint["type"]; displayName: string; configuredPath: string; resolvedPath: string; source: "docker-host" | "default" | "docker-desktop" | "rootless" | "manual"; available: boolean; }
export const isWindows = (platform = process.platform) => platform === "win32";
export function defaultLocalEndpoint(platform = process.platform): LocalDockerEndpoint { return isWindows(platform) ? { type: "windows-named-pipe", pipePath: "//./pipe/docker_engine" } : { type: "unix-socket", socketPath: "/var/run/docker.sock" }; }
export function normalizeLocalEndpoint(endpoint: LocalDockerEndpoint, home = homedir()): LocalDockerEndpoint {
  if (endpoint.type === "windows-named-pipe") { const pipe = endpoint.pipePath.replace(/\\/g, "/"); if (!/^\/\/\.\/pipe\/[A-Za-z0-9_.-]+$/.test(pipe)) throw localError("LOCAL_PIPE_PATH_INVALID", "The named pipe path is invalid."); return { type: "windows-named-pipe", pipePath: pipe }; }
  const value = endpoint.socketPath.trim(); if (!value) throw localError("LOCAL_SOCKET_REQUIRED", "A local Docker socket path is required."); const expanded = value === "~" ? home : value.startsWith("~/") ? `${home}${value.slice(1)}` : value; const path = normalize(resolve(expanded)); if (!path.startsWith("/")) throw localError("LOCAL_SOCKET_PATH_INVALID", "The local Docker socket path must be absolute."); return { type: "unix-socket", socketPath: path };
}
export async function resolveUnixSocket(configuredPath: string, home = homedir()): Promise<ResolvedUnixSocket> { const endpoint = normalizeLocalEndpoint({ type: "unix-socket", socketPath: configuredPath }, home) as Extract<LocalDockerEndpoint, { type: "unix-socket" }>; const expandedPath = endpoint.socketPath; try { const initial = await lstat(expandedPath); if (!initial.isSymbolicLink()) return { configuredPath, expandedPath, resolvedPath: expandedPath, exists: true, isSymbolicLink: false, targetExists: true, isSocket: initial.isSocket() }; try { const resolvedPath = await realpath(expandedPath); const target = await stat(resolvedPath); return { configuredPath, expandedPath, resolvedPath, exists: true, isSymbolicLink: true, linkTarget: resolvedPath, targetExists: true, isSocket: target.isSocket() }; } catch (error) { const code = error && typeof error === "object" ? (error as NodeJS.ErrnoException).code : undefined; if (code === "ELOOP") throw localError("LOCAL_SOCKET_SYMLINK_LOOP", "The configured Docker socket contains a symbolic-link loop."); throw localError("LOCAL_SOCKET_BROKEN_SYMLINK", "The configured Docker socket is a symbolic link whose target does not exist. Docker may not be running."); } } catch (error) { if (isLocalError(error)) throw error; const code = error && typeof error === "object" ? (error as NodeJS.ErrnoException).code : undefined; if (code === "EACCES" || code === "EPERM") throw localError("LOCAL_SOCKET_PERMISSION_DENIED", "Permission was denied for the local Docker socket."); throw localError("LOCAL_SOCKET_NOT_FOUND", "Docker socket not found. Docker may not be running, or it may use a different socket."); } }
export async function validateUnixSocket(endpoint: LocalDockerEndpoint): Promise<LocalDockerEndpoint> { const normalized = normalizeLocalEndpoint(endpoint); if (normalized.type !== "unix-socket") return normalized; const resolved = await resolveUnixSocket(normalized.socketPath); if (!resolved.isSocket) throw localError(resolved.isSymbolicLink ? "LOCAL_SOCKET_TARGET_NOT_A_SOCKET" : "LOCAL_SOCKET_NOT_A_SOCKET", resolved.isSymbolicLink ? "The Docker socket link target is not a Unix socket." : "The local Docker path is not a Unix socket."); return { type: "unix-socket", socketPath: resolved.resolvedPath }; }
export async function discoverLocalDockerEndpoints(environment: NodeJS.ProcessEnv = process.env, platform = process.platform, home = homedir(), uid = typeof process.getuid === "function" ? process.getuid() : undefined): Promise<LocalDockerEndpoint[]> {
  if (isWindows(platform)) { const candidates = [environment.DOCKER_HOST?.replace(/^npipe:\/\//, ""), "//./pipe/docker_engine"].filter((value): value is string => Boolean(value)).filter((value) => /^\/\/\.\/pipe\//.test(value)); return unique(candidates.map((pipePath) => normalizeLocalEndpoint({ type: "windows-named-pipe", pipePath }) as Extract<LocalDockerEndpoint, { type: "windows-named-pipe" }>)); }
  const dockerHost = environment.DOCKER_HOST?.match(/^unix:\/\/(.+)$/)?.[1]; const candidates = [dockerHost, "/var/run/docker.sock", `${home}/.docker/run/docker.sock`, environment.XDG_RUNTIME_DIR ? `${environment.XDG_RUNTIME_DIR}/docker.sock` : undefined, uid === undefined ? undefined : `/run/user/${uid}/docker.sock`].filter((value): value is string => Boolean(value)); const found: LocalDockerEndpoint[] = []; for (const socketPath of candidates) { try { found.push(await validateUnixSocket({ type: "unix-socket", socketPath })); } catch {} } return unique(found);
}
export async function discoverLocalEndpointCandidates(environment: NodeJS.ProcessEnv = process.env, platform = process.platform, home = homedir(), uid = typeof process.getuid === "function" ? process.getuid() : undefined): Promise<LocalEndpointCandidate[]> { const endpoints = await discoverLocalDockerEndpoints(environment, platform, home, uid); return endpoints.map((endpoint, index) => { const configuredPath = endpoint.type === "unix-socket" ? endpoint.socketPath : endpoint.pipePath; const source = configuredPath === "/var/run/docker.sock" ? "default" : configuredPath.includes(".docker/run") ? "docker-desktop" : configuredPath.includes("/run/user/") ? "rootless" : environment.DOCKER_HOST?.includes(configuredPath) ? "docker-host" : "manual"; return { id: `${endpoint.type}:${configuredPath}`, type: endpoint.type, displayName: displayLocalPath(configuredPath, home), configuredPath, resolvedPath: configuredPath, source, available: true }; }); }
export function displayLocalPath(path: string, home = homedir()): string { return path.startsWith(`${home}/`) ? `~/${path.slice(home.length + 1)}` : path; }
function unique(endpoints: LocalDockerEndpoint[]): LocalDockerEndpoint[] { return endpoints.filter((endpoint, index, all) => all.findIndex((candidate) => JSON.stringify(candidate) === JSON.stringify(endpoint)) === index); }
function localError(code: string, message: string): Error & { code: string } { return Object.assign(new Error(message), { code }); }
function isLocalError(error: unknown): error is Error & { code: string } { return Boolean(error && typeof error === "object" && "code" in error && String((error as { code: unknown }).code).startsWith("LOCAL_")); }
