import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import type { DockerContainerSummary } from "../src/containers/ContainerModels";
import { applicationContainer, buildDockerApplications, filterDockerApplications, sortDockerApplications } from "../src/applications/ApplicationSelectors";
import { getDockerComposeMetadata } from "../src/containers/DockerComposeMetadata";
import type { ApplicationFilters } from "../src/applications/ApplicationModels";

function container(id: string, project?: string, service?: string, overrides: Partial<DockerContainerSummary> = {}): DockerContainerSummary { return { id, shortId: id.slice(0, 12), names: [id], displayName: id, image: "example/web:latest", createdAt: "", createdTimestamp: 0, state: "running", statusText: "Up", health: "healthy", ports: [], mounts: [], networks: [{ name: "app-net" }], labels: { ...(project ? { "com.docker.compose.project": project } : {}), ...(service ? { "com.docker.compose.service": service } : {}) }, hostProfileId: "host", mapperWarnings: [], ...overrides }; }
const statuses = (ids: string[] = []) => new Map(ids.map((id) => [`host:${id}`, { state: "available" } as never]));
const filters = (partial: Partial<ApplicationFilters> = {}): ApplicationFilters => ({ search: "", status: "all", updatesOnly: false, sort: "name-asc", ...partial });

describe("Compose application selectors", () => {
  it("groups only real Compose project labels and excludes standalone containers", () => { const apps = buildDockerApplications([container("web", "immich", "server"), container("db", "immich", "database"), container("solo")], statuses()); expect(apps).toHaveLength(1); expect(apps[0]).toMatchObject({ projectName: "immich", serviceCount: 2, containerCount: 2 }); });
  it("keeps replicated containers together under one service", () => { const [app] = buildDockerApplications([container("web-1", "site", "web"), container("web-2", "site", "web")], statuses()); expect(app.services).toEqual([expect.objectContaining({ serviceName: "web", containerCount: 2, runningCount: 2 })]); });
  it("maps Compose project/service, Docker container name, and image independently", () => { const ghost = container("juliarosedelane-ghost", "juliarosedelane", "juliarosedelane-ghost", { image: "ghost:5-alpine" }); const database = container("juliarosedelane-ghost-db", "juliarosedelane", "juliarosedelane-ghost-db", { image: "mysql:8.4" }); const [app] = buildDockerApplications([ghost, database], statuses()); expect(app).toMatchObject({ projectName: "juliarosedelane", imageReferences: ["ghost:5-alpine", "mysql:8.4"] }); expect(app.services.map((service) => service.serviceName)).toEqual(["juliarosedelane-ghost", "juliarosedelane-ghost-db"]); expect([applicationContainer(ghost, statuses()), applicationContainer(database, statuses())]).toEqual([expect.objectContaining({ displayName: "juliarosedelane-ghost", serviceName: "juliarosedelane-ghost" }), expect.objectContaining({ displayName: "juliarosedelane-ghost-db", serviceName: "juliarosedelane-ghost-db" })]); });
  it("preserves the exact live service label even when it starts with the project name", () => { const [ghost] = buildDockerApplications([container("wolf359-ghost-db", "ghost", "ghost-db"), container("wolf359-ghost", "ghost", "ghost")], statuses()); const [umami] = buildDockerApplications([container("umami", "umami", "umami"), container("umami-db", "umami", "umami-db")], statuses()); expect(ghost.services.map((service) => service.serviceName)).toEqual(["ghost", "ghost-db"]); expect(umami.services.map((service) => service.serviceName)).toEqual(["umami", "umami-db"]); });
  it("groups replicas by the Compose service label even when container names differ", () => { const [app] = buildDockerApplications([container("myapp-web-1", "myapp", "web"), container("myapp-web-2", "myapp", "web")], statuses()); expect(app).toMatchObject({ serviceCount: 1, containerCount: 2 }); expect(app.services[0].serviceName).toBe("web"); });
  it("isolates same-named Compose projects by profile ID", () => { const apps = buildDockerApplications([container("web-a", "site", "web", { hostProfileId: "host-a" }), container("web-b", "site", "web", { hostProfileId: "host-b" })], statuses()); expect(apps).toEqual(expect.arrayContaining([expect.objectContaining({ profileId: "host-a", projectName: "site", containerIds: ["web-a"] }), expect.objectContaining({ profileId: "host-b", projectName: "site", containerIds: ["web-b"] })])); });
  it("keeps an unlabelled Compose container in its labelled project without guessing a service", () => { const unlabelled = container("weird-project-container", "example"); const [app] = buildDockerApplications([unlabelled], statuses()); expect(app).toMatchObject({ projectName: "example", serviceCount: 1 }); expect(app.services[0].serviceName).toBe("Unlabelled Compose container"); expect(applicationContainer(unlabelled, statuses())).toMatchObject({ displayName: "weird-project-container", serviceName: "Unlabelled Compose container" }); });
  it("extracts only valid official Compose labels and never reads a container name", () => { expect(getDockerComposeMetadata({ "com.docker.compose.project": " app ", "com.docker.compose.service": " api ", "com.docker.compose.container-number": "2", "com.docker.compose.oneoff": "True", "com.docker.compose.project.config_files": "compose.yml, override.yml" })).toEqual({ project: "app", service: "api", containerNumber: 2, oneOff: true, configFiles: ["compose.yml", "override.yml"] }); expect(getDockerComposeMetadata({ "com.docker.compose.service": "api" })).toBeUndefined(); expect(getDockerComposeMetadata({ "com.docker.compose.project": "app", "com.docker.compose.container-number": "2bad" })?.containerNumber).toBeUndefined(); });
  it("includes one-off containers in totals but excludes stopped one-offs from normal health", () => { const [app] = buildDockerApplications([container("web", "site", "web"), container("job", "site", "job", { state: "exited", health: "unhealthy", labels: { "com.docker.compose.project": "site", "com.docker.compose.service": "job", "com.docker.compose.oneoff": "True" } })], statuses()); expect(app.containerCount).toBe(2); expect(app.unhealthyCount).toBe(1); expect(app.status).toBe("healthy"); });
  it("derives healthy, degraded, mixed, stopped, and unknown statuses conservatively", () => { expect(buildDockerApplications([container("a", "healthy", "web")], statuses())[0].status).toBe("healthy"); expect(buildDockerApplications([container("a", "degraded", "web", { health: "unhealthy" })], statuses())[0].status).toBe("degraded"); expect(buildDockerApplications([container("a", "mixed", "web"), container("b", "mixed", "db", { state: "exited", health: "none" })], statuses())[0].status).toBe("mixed"); expect(buildDockerApplications([container("a", "stopped", "web", { state: "exited", health: "none" })], statuses())[0].status).toBe("stopped"); expect(buildDockerApplications([container("a", "unknown", "web", { state: "unknown", health: "unknown" })], statuses())[0].status).toBe("unknown"); });
  it("counts only existing available update statuses and supports search/status/update filters", () => { const apps = buildDockerApplications([container("a", "immich", "web"), container("b", "ghost", "web", { state: "exited", health: "none" })], statuses(["a"])); expect(apps.find((app) => app.projectName === "immich")?.updateAvailableCount).toBe(1); expect(filterDockerApplications(apps, filters({ search: "imm" }))).toHaveLength(1); expect(filterDockerApplications(apps, filters({ status: "stopped" }))).toHaveLength(1); expect(filterDockerApplications(apps, filters({ updatesOnly: true }))).toHaveLength(1); });
  it("sorts without reparsing labels and remains practical for large snapshots", () => { const containers = Array.from({ length: 500 }, (_, index) => container(`c${index}`, `project-${index % 100}`, `service-${index % 3}`)); const started = performance.now(); const apps = buildDockerApplications(containers, statuses()); const result = sortDockerApplications(apps, "container-count"); expect(apps).toHaveLength(100); expect(result[0].containerCount).toBe(5); expect(performance.now() - started).toBeLessThan(500); });
  it("keeps Applications snapshot-only and leaves Compose mutation unavailable", async () => { const [tab, selectors, compose, dashboard, api] = await Promise.all([readFile("src/applications/ApplicationsTab.ts", "utf8"), readFile("src/applications/ApplicationSelectors.ts", "utf8"), readFile("src/containers/DockerComposeMetadata.ts", "utf8"), readFile("src/views/DockerDashboardView.ts", "utf8"), readFile("src/services/DockerApiClient.ts", "utf8")]); expect(tab).toContain("openContainer"); expect(tab).not.toMatch(/child_process|spawn\(|exec(File)?\(|method:\s*"(?:POST|DELETE)"/); expect(selectors).toContain("getDockerComposeMetadata"); expect(selectors).not.toMatch(/splitContainerName|removeProjectPrefix|deriveServiceFromName/); expect(compose).toContain("com.docker.compose.project"); expect(dashboard).toContain('label: "Applications"'); expect(api).toContain('method: "GET"'); });
  it("uses a semantic, resilient card structure and responsive scoped layout", async () => { const [tab, css, dashboard] = await Promise.all([readFile("src/applications/ApplicationsTab.ts", "utf8"), readFile("styles.css", "utf8"), readFile("src/views/DockerDashboardView.ts", "utf8")]); for (const cls of ["application-card-header", "application-summary", "application-services", "application-service-chips", "application-footer", "application-container-row"]) expect(tab).toContain(cls); expect(tab).toContain("slice(0, 5)"); expect(tab).toContain("+${application.services.length - 5} more"); expect(css).toContain(".docker-connector__applications-layout { display: grid; grid-template-columns: minmax(0, 1fr);"); expect(css).toContain(".docker-connector__applications-layout.is-detail-open"); expect(css).toContain("height: auto"); expect(css).toContain("flex-wrap: wrap"); expect(css).toContain("@container (max-width: 520px)"); expect(css).not.toMatch(/\.docker-connector__application-card[^}]*position:\s*absolute/); expect(dashboard).toContain("is-active"); });
  it("keeps application inspector rows bounded, pluralized, and responsive", async () => { const [tab, css] = await Promise.all([readFile("src/applications/ApplicationsTab.ts", "utf8"), readFile("styles.css", "utf8")]); for (const cls of ["application-container-row", "application-container-main", "application-container-badges", "application-container-meta", "application-image-row", "application-image-reference", "application-image-counts"]) expect(tab).toContain(cls); expect(tab).toContain("function pluralize"); expect(tab).toContain("formatTimestamp"); expect(tab).toContain("resetDetailScroll"); expect(tab).toContain("detailScrollTop"); expect(tab).toContain("panel.scrollTop"); expect(css).toContain(".docker-connector__application-container-row { display: grid"); expect(css).toContain(".docker-connector__application-image-row { display: grid; grid-template-columns: minmax(0, 1fr) auto"); expect(css).toContain("@container (max-width: 400px)"); expect(css).not.toMatch(/\.docker-connector__application-container-row[^}]*position:\s*absolute/); });
});
