import { describe, expect, it } from "vitest";
import { configuredServerConnection } from "../src/views/ConfiguredServerConnection";
import type { DockerConnectionProfile } from "../src/models/DockerConnectionProfile";

const base = { id: "id", name: "A very long configured server name that remains safely truncated by the card", enabled: true, createdAt: "", updatedAt: "" };
const profiles: DockerConnectionProfile[] = [{ ...base, connectionType: "local", localEndpoint: { type: "unix-socket", socketPath: "/very/long/path/docker.sock" } }, { ...base, connectionType: "docker-context", contextName: "desktop-linux", contextSnapshot: { isCurrentWhenSaved: false, endpointType: "ssh", supported: true, importedAt: "", lastDiscoveredAt: "" } }, { ...base, connectionType: "ssh", sshHost: "server.example.com", sshPort: 22, sshUsername: "user", authentication: { type: "password" }, remoteSocketPath: "/var/run/docker.sock" }, { ...base, id: "key", connectionType: "ssh", sshHost: "server.example.com", sshPort: 22, sshUsername: "user", authentication: { type: "private-key", privateKeyPath: "/key" }, remoteSocketPath: "/var/run/docker.sock" }, { ...base, connectionType: "docker-tls", host: "docker.example.com", port: 2376, serverName: "docker.example.com", caCertificatePath: "/ca", clientCertificatePath: "/cert", clientKeyPath: "/key", tlsSnapshot: { serverName: "docker.example.com", importedAt: "" } }];
describe("configured server connection labels", () => {
  it("maps each configured connection method to canonical visible labels", () => expect(profiles.map(configuredServerConnection)).toEqual([{ label: "Local Docker Socket", detail: "Local Docker Unix socket" }, { label: "Docker Context", detail: "Docker Context: desktop-linux" }, { label: "Remote Docker via SSH", detail: "SSH Host: server.example.com · Password" }, { label: "Remote Docker via SSH", detail: "SSH Host: server.example.com · Private Key" }, { label: "Remote Docker API (Mutual TLS)", detail: "Docker Host: docker.example.com:2376" }]));
});
