import { describe, expect, it } from "vitest";
import { buildContainerRecreatePlan, getContainerUpdateEligibility, isComposeManaged, isPullableImageReference } from "../src/services/ContainerUpdatePlan";

const inspect = { Id: "a".repeat(64), Name: "/web", Config: { Image: "nginx:1.27", Env: ["PASSWORD=secret", "PORT=80"], Cmd: ["nginx"], Labels: { safe: "yes" }, ExposedPorts: { "80/tcp": {} } }, Image: "sha256:old", State: { Running: true }, HostConfig: { Binds: ["data:/data"], PortBindings: { "80/tcp": [{ HostPort: "8080" }] }, RestartPolicy: { Name: "always" } }, Mounts: [{ Type: "volume" }], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge", Aliases: ["web"] } } } };
describe("container recreate plan", () => {
  it("maps only create fields, keeps environment values in memory, and retains the primary network", () => { const plan = buildContainerRecreatePlan(inspect); expect(plan.createPayload).toMatchObject({ Image: "nginx:1.27", HostConfig: { Binds: ["data:/data"] }, NetworkingConfig: { EndpointsConfig: { bridge: { Aliases: ["web"] } } } }); expect(plan.environmentCount).toBe(2); expect(JSON.stringify({ environmentCount: plan.environmentCount })).not.toContain("secret"); expect(plan.networks[0]).toMatchObject({ name: "bridge", aliases: ["web"] }); });
  it("blocks compose and unsupported rollback-risking configuration", () => { expect(() => buildContainerRecreatePlan({ ...inspect, Config: { ...inspect.Config, Labels: { "com.docker.compose.project": "app" } } })).toThrow(/Compose/); expect(() => buildContainerRecreatePlan({ ...inspect, HostConfig: { ...inspect.HostConfig, AutoRemove: true } })).toThrow(/unsupported/); });
  it("recognizes normal pullable image references including ghost:5-alpine", () => { ["ghost:5-alpine", "mysql:8.4", "portainer/portainer-ce:latest", "ghcr.io/example/app:stable", "registry.example.com:5000/team/app:production"].forEach((image) => expect(isPullableImageReference(image)).toBe(true)); expect(getContainerUpdateEligibility("ghost:5-alpine", { ordinary: "label" })).toEqual({ eligible: true, imageReference: "ghost:5-alpine", composeManaged: false }); });
  it("blocks only recognized Compose labels and unsafe image references", () => { expect(isComposeManaged({ ordinary: "label", project: "example" })).toBe(false); expect(getContainerUpdateEligibility("ghost:5-alpine", { "com.docker.compose.service": "ghost" })).toMatchObject({ eligible: false, reasonCode: "CONTAINER_UPDATE_COMPOSE_MANAGED", composeManaged: true }); ["sha256:abcdef", "ghost@sha256:abcdef", "ghost", "not a ref:tag"].forEach((image) => expect(getContainerUpdateEligibility(image, {})).toMatchObject({ eligible: false, reasonCode: "CONTAINER_UPDATE_IMAGE_UNPULLABLE" })); });
});
