import { describe, expect, it } from "vitest";
import { activeFilterLabels, matchesSearch, resultCountText, selectContainers, uniqueNetworks, updateKey } from "../src/containers/ContainerSelectors";
import { DEFAULT_CONTAINERS_VIEW_STATE, type DockerContainerSummary } from "../src/containers/ContainerModels";

const make = (name: string, state: DockerContainerSummary["state"] = "running", overrides: Partial<DockerContainerSummary> = {}): DockerContainerSummary => ({ id: `${name}-full-id`, shortId: name, names: [name], displayName: name, image: "repo/app:1", createdAt: "2026-01-01T00:00:00.000Z", createdTimestamp: 1, state, statusText: state, health: "none", ports: [{ privatePort: 80, publicPort: 8080, protocol: "tcp", ip: "0.0.0.0", type: "published" }], mounts: [{ type: "bind", source: "/srv/app", destination: "/app" }], networks: [{ name: "frontend" }], labels: { "com.example.role": "web" }, hostProfileId: "host", mapperWarnings: [], ...overrides });

describe("container selectors", () => {
  it("searches name, identifiers, ports, networks, mounts and labels case-insensitively", () => { const container = make("container-10"); ["CONTAINER", "full-id", "8080", "frontend", "/srv/app", "com.example.role", "web"].forEach((query) => expect(matchesSearch(container, query)).toBe(true)); });
  it("filters grouped stopped state without treating paused as stopped", () => { const state = { ...DEFAULT_CONTAINERS_VIEW_STATE, stateFilter: "stopped" as const }; expect(selectContainers([make("exit", "exited"), make("dead", "dead"), make("created", "created"), make("pause", "paused")], state).map((item) => item.displayName)).toEqual(["created", "dead", "exit"]); });
  it("combines filters and sorts natural names deterministically", () => { const state = { ...DEFAULT_CONTAINERS_VIEW_STATE, stateFilter: "running" as const, healthFilter: "healthy" as const, networkFilter: "frontend", sortMode: "name-asc" as const }; expect(selectContainers([make("container-10", "running", { health: "healthy" }), make("container-2", "running", { health: "healthy" }), make("other", "running", { health: "unhealthy" })], state).map((item) => item.displayName)).toEqual(["container-2", "container-10"]); });
  it("applies the available-update filter after the other filters and preserves sorting", () => { const first = make("web-10", "running", { health: "healthy" }), second = make("web-2", "running", { health: "healthy" }), ignored = make("api", "running", { health: "healthy" }); const state = { ...DEFAULT_CONTAINERS_VIEW_STATE, updatesOnly: true, searchQuery: "web", healthFilter: "healthy" as const, networkFilter: "frontend", sortMode: "name-asc" as const }; const available = new Set([updateKey("host", first.id), updateKey("host", second.id)]); expect(selectContainers([first, second, ignored], state, available).map((item) => item.displayName)).toEqual(["web-2", "web-10"]); });
  it("adds and clears only the Updates available filter chip", () => { const state = { ...DEFAULT_CONTAINERS_VIEW_STATE, updatesOnly: true, searchQuery: "web", networkFilter: "frontend" }; expect(activeFilterLabels(state)).toEqual(expect.arrayContaining([{ id: "updates", label: "Updates available" }, { id: "search", label: "Search: web" }, { id: "network", label: "Network: frontend" }])); });
  it("reports active filters, unique networks, and correct count wording", () => { const state = { ...DEFAULT_CONTAINERS_VIEW_STATE, searchQuery: "web", stateFilter: "running" as const }; expect(activeFilterLabels(state)).toHaveLength(2); expect(uniqueNetworks([make("a"), make("b", "running", { networks: [{ name: "backend" }] })])).toEqual(["backend", "frontend"]); expect(resultCountText(1, 1)).toBe("1 container"); expect(resultCountText(2, 4)).toBe("2 of 4 containers"); });
});
