import { describe, expect, it } from "vitest";
import { readFile } from "node:fs/promises";

describe("container management settings propagation", () => {
  it("is disabled by default", async () => { const settings = await readFile("src/settings/settings.ts", "utf8"); expect(settings).toMatch(/containerManagementEnabled:\s*false/); });
  it("uses one canonical persisted setting and emits only after a successful save", async () => { const [settings, main, view, tab] = await Promise.all([readFile("src/settings/settings.ts", "utf8"), readFile("src/main.ts", "utf8"), readFile("src/views/DockerDashboardView.ts", "utf8"), readFile("src/containers/ContainersTab.ts", "utf8")]); expect(settings).toMatch(/setContainerManagementEnabled\(requestedValue\)/); expect(main).toMatch(/setContainerManagementEnabled\(value: boolean\): Promise<boolean>/); expect(main).toMatch(/await this\.saveSettings\(\);[\s\S]*emitSettingsChanged/); expect(main).toMatch(/catch \(error\) \{\s*this\.settings\.containerManagementEnabled = previousValue;/); expect(view).toMatch(/onSettingsChanged/); expect(view).toMatch(/removeSettingsListener/); expect(tab).toMatch(/this\.plugin\.settings\.containerManagementEnabled/); });
  it("loads a persisted true value without a false-coercing migration", async () => { const main = await readFile("src/main.ts", "utf8"); expect(main).toMatch(/containerManagementEnabled:\s*modernSettings\.containerManagementEnabled === true/); expect(main).not.toMatch(/containerManagementEnabled\s*:\s.*\|\|\s*false/); });
  it("makes confirmation, saving, success, and failure states observable", async () => { const settings = await readFile("src/settings/settings.ts", "utf8"); expect(settings).toMatch(/containerManagementSaveInProgress/); expect(settings).toMatch(/toggle\.setDisabled\(true\)/); expect(settings).toMatch(/Status: Saving…/); expect(settings).toMatch(/Status: Save failed/); expect(settings).toMatch(/Container management enabled\./); expect(settings).toMatch(/Container management disabled\./); expect(settings).toMatch(/Could not save Container management setting:/); expect(settings).toMatch(/toSafeSettingsErrorMessage/); });
  it("serializes settings persistence against the current authoritative object", async () => { const main = await readFile("src/main.ts", "utf8"); expect(main).toMatch(/private settingsSaveChain: Promise<void> = Promise\.resolve\(\)/); expect(main).toMatch(/this\.settingsSaveChain\.then\(async \(\) => \{\s*await this\.saveData\(this\.settings\);/); expect(main).toMatch(/this\.settingsSaveChain = save\.catch\(\(\) => undefined\)/); });
  it("guards programmatic toggle rollback from recursive saves", async () => { const settings = await readFile("src/settings/settings.ts", "utf8"); expect(settings).toMatch(/containerManagementProgrammaticChange/); expect(settings).toMatch(/if \(this\.containerManagementProgrammaticChange \|\| this\.containerManagementSaveInProgress\) return/); });
});
