import { describe, expect, it, vi } from "vitest";
import { DockerContainerActionService } from "../src/services/DockerContainerActionService";
import type { DockerConnectionProfile } from "../src/models/DockerConnectionProfile";
import { DockerConnectionError } from "../src/connections/DockerTransport";

const profile: DockerConnectionProfile = { id: "host", name: "Host", connectionType: "local", enabled: true, createdAt: "2026-01-01", updatedAt: "2026-01-01", localEndpoint: { type: "unix-socket", socketPath: "/var/run/docker.sock" } };
const id = "a".repeat(64);
function subject(enabled = true) { const request = vi.fn().mockResolvedValue(undefined); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => enabled); return { service, request }; }

describe("DockerContainerActionService", () => {
  it("is disabled by default policy and never reaches a transport", async () => { const { service, request } = subject(false); await expect(service.start(profile, id)).rejects.toMatchObject({ code: "CONTAINER_ACTIONS_DISABLED" }); expect(request).not.toHaveBeenCalled(); });
  it("enforces the backend management gate for every lifecycle and update entry point", async () => { const { service, request } = subject(false); await expect(service.start(profile, id)).rejects.toMatchObject({ code: "CONTAINER_ACTIONS_DISABLED" }); await expect(service.stop(profile, id, 10)).rejects.toMatchObject({ code: "CONTAINER_ACTIONS_DISABLED" }); await expect(service.stop(profile, id, 30, true)).rejects.toMatchObject({ code: "CONTAINER_ACTIONS_DISABLED" }); await expect(service.restart(profile, id, 10)).rejects.toMatchObject({ code: "CONTAINER_ACTIONS_DISABLED" }); await expect(service.update(profile, id)).rejects.toMatchObject({ code: "CONTAINER_ACTIONS_DISABLED" }); expect(request).not.toHaveBeenCalled(); });
  it("uses full trusted IDs with explicit empty lifecycle responses through the dedicated routes", async () => { const { service, request } = subject(); await service.start(profile, id); await service.stop(profile, id, 10); await service.stop(profile, id, 30, true); await service.restart(profile, id, 60); expect(request.mock.calls.map(([request]) => request)).toEqual([{ method: "POST", path: `/containers/${id}/start`, responseType: "empty" }, { method: "POST", path: `/containers/${id}/stop?t=10`, responseType: "empty" }, { method: "POST", path: `/containers/${id}/stop?t=30`, responseType: "empty" }, { method: "POST", path: `/containers/${id}/restart?t=60`, responseType: "empty" }]); expect(request.mock.calls[0][0].path).not.toBe(`/containers/${id.slice(0, 12)}/start`); });
  it("uses the owning profile rather than a default or similarly named host", async () => { const request = vi.fn().mockResolvedValue(undefined); const create = vi.fn(() => ({ request })); const service = new DockerContainerActionService({ create } as never, () => true); await service.start(profile, id); expect(create).toHaveBeenCalledTimes(1); expect(create).toHaveBeenCalledWith(profile); });
  it("rejects arbitrary identities and fails update safely before mutation when inspect data is unsupported", async () => { const { service, request } = subject(); await expect(service.start(profile, "../x")).rejects.toMatchObject({ code: "CONTAINER_NOT_FOUND" }); await expect(service.update(profile, id)).resolves.toEqual({ status: "failed-before-mutation", errorCode: "CONTAINER_UPDATE_CONFIG_UNSUPPORTED" }); expect(request.mock.calls.every(([call]) => call.method === "GET")).toBe(true); });
  it("keeps a safe Update eligibility failure available to the action panel", async () => { const { service } = subject(); await expect(service.update(profile, id)).resolves.toEqual({ status: "failed-before-mutation", errorCode: "CONTAINER_UPDATE_CONFIG_UNSUPPORTED" }); expect(service.state(profile.id, id)).toMatchObject({ action: "update", state: "failed", failure: { action: "update", errorCode: "CONTAINER_UPDATE_CONFIG_UNSUPPORTED", safeMessage: expect.stringMatching(/unsupported/) } }); expect(service.isActive(profile.id, id)).toBe(false); });
  it("tracks a safe lifecycle failure", async () => { const { service, request } = subject(); request.mockRejectedValueOnce(new Error("nope")); await expect(service.restart(profile, id, 10)).rejects.toMatchObject({ code: "CONTAINER_RESTART_FAILED" }); expect(service.state(profile.id, id)).toMatchObject({ state: "failed", action: "restart" }); });
  it("maps a safe Docker start conflict and retains failure details after releasing the action lock", async () => { const { service, request } = subject(); request.mockRejectedValueOnce(new DockerConnectionError("DOCKER_HTTP_FAILED", "Docker API returned HTTP 409. Port is already allocated.", "Port is already allocated.", 409)); await expect(service.start(profile, id)).rejects.toMatchObject({ code: "CONTAINER_START_CONFLICT" }); expect(service.state(profile.id, id)).toMatchObject({ state: "failed", action: "start", errorCode: "CONTAINER_START_CONFLICT", failure: { safeDetails: { httpStatus: 409, dockerMessage: "Port is already allocated." } } }); await service.start(profile, id); expect(request).toHaveBeenCalledTimes(2); });
  it("rejects rapid duplicate lifecycle actions without issuing a second mutation", async () => { let release: (() => void) | undefined; const pending = new Promise<void>((resolve) => { release = resolve; }); const request = vi.fn(async () => pending); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); const first = service.restart(profile, id, 10); await expect(service.restart(profile, id, 10)).rejects.toMatchObject({ code: "CONTAINER_ACTION_ALREADY_RUNNING" }); expect(request).toHaveBeenCalledOnce(); release?.(); await first; expect(service.state(profile.id, id)).toMatchObject({ state: "succeeded" }); });
  it("performs backup-first recreation and removes the stopped backup without volumes", async () => { const inspect = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Env: ["SECRET=value"], Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; const requests: Array<{ method: string; path: string }> = []; const request = vi.fn(async (call: { method: string; path: string }) => { requests.push(call); if (call.path.endsWith(`/containers/${id}/json`)) return inspect; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.includes("/containers/create")) return { Id: "b".repeat(64) }; if (call.path.endsWith(`/containers/${"b".repeat(64)}/json`)) return { State: { Running: true } }; return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); const result = await service.update(profile, id); expect(result).toMatchObject({ status: "updated", oldContainerId: id, newContainerId: "b".repeat(64) }); expect(requests.filter((call) => call.method === "POST").map((call) => call.path)).toEqual(expect.arrayContaining([expect.stringMatching(`/containers/${id}/stop`), expect.stringMatching(`/containers/${id}/rename`), expect.stringMatching("/containers/create"), expect.stringMatching(`/containers/${"b".repeat(64)}/start`)])); expect(requests.find((call) => call.method === "DELETE")?.path).toBe(`/containers/${id}?v=false&force=false`); });
  it("recreates a standalone container with exact captured configuration before safe backup cleanup", async () => {
    const replacement = "b".repeat(64);
    const original = { Id: id, Name: "/web", Config: { Image: "registry.example.test/team/web:2.0", Env: ["SECRET_TOKEN=do-not-render", "PORT=8080"], Cmd: ["node", "server.js"], Entrypoint: ["/entrypoint.sh"], WorkingDir: "/srv/web", User: "1001:1001", Labels: { "com.example.role": "web" }, Healthcheck: { Test: ["CMD", "true"] } }, Image: "sha256:old", State: { Running: true }, HostConfig: { RestartPolicy: { Name: "unless-stopped" }, PortBindings: { "80/tcp": [{ HostIp: "127.0.0.1", HostPort: "8080" }], "53/udp": [{ HostPort: "5353" }] }, Binds: ["site-data:/var/lib/site", "/srv/host-config:/etc/site:ro"] }, Mounts: [{ Type: "volume" }, { Type: "bind" }], NetworkSettings: { Networks: { "app-primary": { NetworkID: "network-primary", Aliases: ["web"] }, "app-secondary": { NetworkID: "network-secondary", Aliases: ["web-secondary"] } } } };
    const calls: Array<{ method: string; path: string; body?: string }> = [];
    const request = vi.fn(async (call: { method: string; path: string; body?: string }) => { calls.push(call); if (call.path.endsWith(`/containers/${id}/json`)) return original; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["registry.example.test/team/web:2.0"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.startsWith("/containers/create")) return { Id: replacement }; if (call.path.endsWith(`/containers/${replacement}/json`)) return { State: { Running: true, Health: { Status: "healthy" } } }; return undefined; });
    const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true);
    const result = await service.update(profile, id);
    expect(result).toEqual({ status: "updated", oldContainerId: id, newContainerId: replacement, oldImageId: "sha256:old", newImageId: "sha256:new" });
    const create = calls.find((call) => call.path.startsWith("/containers/create"))!;
    expect(create.path).toBe("/containers/create?name=web");
    expect(JSON.parse(create.body!)).toMatchObject({ Image: "registry.example.test/team/web:2.0", Env: ["SECRET_TOKEN=do-not-render", "PORT=8080"], Cmd: ["node", "server.js"], Entrypoint: ["/entrypoint.sh"], WorkingDir: "/srv/web", User: "1001:1001", HostConfig: { RestartPolicy: { Name: "unless-stopped" }, PortBindings: original.HostConfig.PortBindings, Binds: original.HostConfig.Binds }, NetworkingConfig: { EndpointsConfig: { "app-primary": { Aliases: ["web"] } } } });
    expect(calls.map((call) => call.path)).toEqual([`/containers/${id}/json`, "/images/create?fromImage=registry.example.test%2Fteam%2Fweb&tag=2.0", "/images/json", "/containers/json?all=true", `/containers/${id}/stop?t=30`, expect.stringMatching(new RegExp(`^/containers/${id}/rename\\?name=web\\.docker-connector-backup-`)), "/containers/create?name=web", "/networks/network-secondary/connect", `/containers/${replacement}/start`, `/containers/${replacement}/json`, `/containers/${id}?v=false&force=false`]);
    expect(calls.find((call) => call.path === "/networks/network-secondary/connect")?.body).toBe(JSON.stringify({ Container: replacement, EndpointConfig: { Aliases: ["web-secondary"] } }));
    expect(calls.filter((call) => call.method === "DELETE").map((call) => call.path)).toEqual([`/containers/${id}?v=false&force=false`]);
    expect(JSON.stringify(result)).not.toContain("do-not-render");
    expect(service.activeUpdateCount()).toBe(0);
  });
  it("waits for a configured health check to become healthy before backup cleanup", async () => {
    const replacement = "b".repeat(64); let replacementInspects = 0; let now = 0; const waits: number[] = [];
    const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {}, Healthcheck: { Test: ["CMD", "true"] } }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } };
    const paths: string[] = [];
    const request = vi.fn(async (call: { path: string }) => { paths.push(call.path); if (call.path.endsWith(`/containers/${id}/json`)) return original; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.startsWith("/containers/create")) return { Id: replacement }; if (call.path.endsWith(`/containers/${replacement}/json`)) return { State: { Running: true, Health: { Status: ++replacementInspects === 1 ? "starting" : "healthy" } } }; return undefined; });
    const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true, () => now, async (milliseconds) => { waits.push(milliseconds); now += milliseconds; });
    await expect(service.update(profile, id)).resolves.toMatchObject({ status: "updated", newContainerId: replacement });
    expect(replacementInspects).toBe(2); expect(waits).toEqual([1_000]);
    expect(paths.indexOf(`/containers/${replacement}/json`)).toBeLessThan(paths.indexOf(`/containers/${id}?v=false&force=false`));
  });
  it("emits safe, scoped progress only at transaction boundaries", async () => { const inspect = { Id: id, Name: "/web", Config: { Image: "ghost:5-alpine", Env: ["SECRET=value"], Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; const replacement = "b".repeat(64); const request = vi.fn(async (call: { path: string }) => { if (call.path.endsWith(`/containers/${id}/json`)) return inspect; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["ghost:5-alpine"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.includes("/containers/create")) return { Id: replacement }; if (call.path.endsWith(`/containers/${replacement}/json`)) return { State: { Running: true } }; return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); const events: unknown[] = []; const remove = service.onUpdateProgress((event) => events.push(event)); await service.update(profile, id); remove(); expect(events).toEqual(expect.arrayContaining([expect.objectContaining({ profileId: profile.id, containerId: id, stage: "inspecting", state: "running" }), expect.objectContaining({ stage: "pulling-image", state: "running" }), expect.objectContaining({ stage: "completed", state: "complete" })])); expect(JSON.stringify(events)).not.toContain("SECRET"); });
  it("rolls back a failed replacement creation using captured container IDs", async () => { const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; let originalInspects = 0; const request = vi.fn(async (call: { path: string }) => { if (call.path.endsWith(`/containers/${id}/json`)) return ++originalInspects === 1 ? original : { State: { Running: true } }; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.includes("/containers/create")) throw new Error("create failed"); return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); await expect(service.update(profile, id)).resolves.toEqual({ status: "failed-rolled-back", originalContainerId: id, errorCode: "CONTAINER_UPDATE_PULL_FAILED" }); expect(request.mock.calls.map(([call]) => call.path)).toEqual(expect.arrayContaining([expect.stringMatching(`/containers/${id}/rename`), expect.stringMatching(`/containers/${id}/start`)])); });
  it("reports incomplete rollback when the original name cannot be restored", async () => { const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; let renames = 0; const request = vi.fn(async (call: { path: string }) => { if (call.path.endsWith(`/containers/${id}/json`)) return original; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.includes("/rename")) { if (++renames > 1) throw new Error("name occupied"); return undefined; } if (call.path.includes("/containers/create")) throw new Error("create failed"); return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); const result = await service.update(profile, id); expect(result).toMatchObject({ status: "failed-rollback-incomplete", errorCode: "CONTAINER_UPDATE_ROLLBACK_FAILED" }); expect(JSON.stringify(result)).not.toContain("SECRET"); });
  it("does not claim successful rollback when Docker omits the identity of a created replacement", async () => { const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; const calls: Array<{ method: string; path: string }> = []; const request = vi.fn(async (call: { method: string; path: string }) => { calls.push(call); if (call.path.endsWith(`/containers/${id}/json`)) return original; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.startsWith("/containers/create")) return {}; return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); await expect(service.update(profile, id)).resolves.toMatchObject({ status: "failed-rollback-incomplete", errorCode: "CONTAINER_UPDATE_ROLLBACK_FAILED", safeRecoveryInstructions: expect.stringMatching(/web/) }); expect(calls.some((call) => call.path.includes(`/containers/${id}/rename`))).toBe(true); expect(calls.some((call) => call.path.endsWith(`/containers/${id}/start`))).toBe(true); expect(calls.filter((call) => call.method === "DELETE").map((call) => call.path)).toEqual([]); expect(service.activeUpdateCount()).toBe(0); });
  it("fails before preservation when stopping the original fails", async () => { const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; const paths: string[] = []; const request = vi.fn(async (call: { path: string }) => { paths.push(call.path); if (call.path.endsWith(`/containers/${id}/json`)) return original; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.includes(`/containers/${id}/stop`)) throw new DockerConnectionError("DOCKER_HTTP_FAILED", "stop failed", undefined, 500); return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); await expect(service.update(profile, id)).resolves.toEqual({ status: "failed-before-mutation", errorCode: "DOCKER_HTTP_FAILED" }); expect(paths.some((path) => path.includes("/rename") || path.includes("/containers/create"))).toBe(false); expect(service.activeUpdateCount()).toBe(0); });
  it("restores an originally stopped container without starting it after replacement creation fails", async () => { const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {} }, Image: "sha256:old", State: { Running: false }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; const paths: string[] = []; const request = vi.fn(async (call: { path: string }) => { paths.push(call.path); if (call.path.endsWith(`/containers/${id}/json`)) return original; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.startsWith("/containers/create")) throw new Error("create failed"); return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); await expect(service.update(profile, id)).resolves.toMatchObject({ status: "failed-rolled-back", originalContainerId: id }); expect(paths.some((path) => path.endsWith(`/containers/${id}/start`))).toBe(false); expect(paths.some((path) => path.includes(`/containers/${id}/rename`))).toBe(true); });
  it("continues safety rollback after management is disabled during a failed replacement start", async () => { const replacement = "b".repeat(64); let enabled = true; const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; const paths: string[] = []; const request = vi.fn(async (call: { path: string }) => { paths.push(call.path); if (call.path.endsWith(`/containers/${id}/json`)) return original; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.startsWith("/containers/create")) { enabled = false; return { Id: replacement }; } if (call.path.endsWith(`/containers/${replacement}/start`)) throw new Error("replacement start failed"); if (call.path.endsWith(`/containers/${id}/json`)) return { State: { Running: true } }; return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => enabled); await expect(service.update(profile, id)).resolves.toMatchObject({ status: "failed-rolled-back", originalContainerId: id }); expect(paths).toEqual(expect.arrayContaining([`/containers/${replacement}?v=false&force=false`, expect.stringMatching(new RegExp(`/containers/${id}/rename`)), `/containers/${id}/start`])); expect(paths.some((path) => /\/volumes|\/networks\/.*(?:delete|remove)|\/images\/.+(?:delete|remove)/.test(path))).toBe(false); });
  it("retains the stopped backup when cleanup fails after verification", async () => { const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; const replacement = "b".repeat(64); const request = vi.fn(async (call: { method: string; path: string }) => { if (call.path.endsWith(`/containers/${id}/json`)) return original; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.includes("/containers/create")) return { Id: replacement }; if (call.path.endsWith(`/containers/${replacement}/json`)) return { State: { Running: true } }; if (call.method === "DELETE") throw new Error("cleanup failed"); return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); await expect(service.update(profile, id)).resolves.toMatchObject({ status: "updated-with-backup-retained", oldContainerId: id, newContainerId: replacement }); });
  it("cancels before mutation without a Docker request", async () => { const { service, request } = subject(); const controller = new AbortController(); controller.abort(); await expect(service.update(profile, id, true, controller.signal)).resolves.toEqual({ status: "cancelled" }); expect(request).not.toHaveBeenCalled(); expect(service.activeUpdateCount()).toBe(0); });
  it("cancels after a confirmed stop and restores the original without rename-back", async () => { const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; const controller = new AbortController(); let inspects = 0; const request = vi.fn(async (call: { path: string }) => { if (call.path.endsWith(`/containers/${id}/json`)) return ++inspects === 1 ? original : { State: { Running: true } }; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.includes("/stop")) { controller.abort(); return undefined; } return undefined; }); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); await expect(service.update(profile, id, true, controller.signal)).resolves.toMatchObject({ status: "failed-rolled-back", originalContainerId: id, errorCode: "CONTAINER_UPDATE_CANCELLED" }); const paths = request.mock.calls.map(([call]) => call.path); expect(paths.some((path: string) => path.includes("/rename"))).toBe(false); expect(paths.some((path: string) => path.endsWith(`/containers/${id}/start`))).toBe(true); });
  it("cancels all active updates for plugin unload and waits for the same rollback path", async () => { const original = { Id: id, Name: "/web", Config: { Image: "nginx:1.27", Labels: {} }, Image: "sha256:old", State: { Running: true }, HostConfig: {}, Mounts: [], NetworkSettings: { Networks: { bridge: { NetworkID: "bridge" } } } }; let inspects = 0; let service: DockerContainerActionService; const request = vi.fn(async (call: { path: string }) => { if (call.path.endsWith(`/containers/${id}/json`)) return ++inspects === 1 ? original : { State: { Running: true } }; if (call.path === "/images/json") return [{ Id: "sha256:new", RepoTags: ["nginx:1.27"] }]; if (call.path === "/containers/json?all=true") return []; if (call.path.includes("/stop")) { service.cancelAllUpdates(); return undefined; } return undefined; }); service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); await expect(service.update(profile, id)).resolves.toMatchObject({ status: "failed-rolled-back", errorCode: "CONTAINER_UPDATE_CANCELLED" }); expect(service.activeUpdateCount()).toBe(0); });
  it("reports no active updates and blocks new actions once unload recovery begins", async () => { const { service } = subject(); await expect(service.recoverActiveUpdates(1)).resolves.toMatchObject({ status: "no-active-updates" }); await expect(service.start(profile, id)).rejects.toMatchObject({ code: "PLUGIN_UNLOADING" }); });
  it("returns an honest bounded timeout for an unsettled active update", async () => { const request = vi.fn(() => new Promise(() => undefined)); const service = new DockerContainerActionService({ create: vi.fn(() => ({ request })) } as never, () => true); void service.update(profile, id); await new Promise((resolve) => setTimeout(resolve, 0)); const result = await service.recoverActiveUpdates(1); expect(result).toMatchObject({ status: "timed-out", transactionResults: [expect.objectContaining({ profileId: profile.id, containerId: id, errorCode: "CONTAINER_UPDATE_UNLOAD_RECOVERY_TIMEOUT" })] }); });
});
