import { describe, expect, it } from "vitest";
import { getContainerActionCapabilities } from "../src/containers/ContainerActionCapabilities";
import { connectionCapabilities } from "../src/connections/DockerConnectionCapabilities";
import type { DockerConnectionProfile } from "../src/models/DockerConnectionProfile";

const local: DockerConnectionProfile = { id: "host", name: "Host", connectionType: "local", enabled: true, createdAt: "x", updatedAt: "x", localEndpoint: { type: "unix-socket", socketPath: "/var/run/docker.sock" } };
const base = { hostStatus: "online", connection: connectionCapabilities(local) } as const;
describe("container action capabilities", () => {
  it("keeps every action disabled until management is explicitly enabled", () => { expect(getContainerActionCapabilities({ ...base, managementEnabled: false, containerState: "running" })).toMatchObject({ canStart: false, canStop: false, canUpdate: false, reason: expect.stringMatching(/disabled/) }); });
  it("renders valid running and stopped lifecycle actions when enabled", () => { expect(getContainerActionCapabilities({ ...base, managementEnabled: true, containerState: "running" })).toMatchObject({ canStart: false, canShutdown: true, canStop: true, canRestart: true, canUpdate: true }); expect(getContainerActionCapabilities({ ...base, managementEnabled: true, containerState: "exited" })).toMatchObject({ canStart: true, canShutdown: false, canStop: false, canUpdate: true }); });
  it("blocks offline, active, and ineligible updates with safe reasons", () => { expect(getContainerActionCapabilities({ ...base, managementEnabled: true, hostStatus: "offline", containerState: "running" }).reason).toMatch(/online/); expect(getContainerActionCapabilities({ ...base, managementEnabled: true, containerState: "running", activeAction: true }).reason).toMatch(/progress/); expect(getContainerActionCapabilities({ ...base, managementEnabled: true, containerState: "running", updateEligibility: { eligible: false, reasonCode: "CONTAINER_UPDATE_COMPOSE_MANAGED", safeReason: "This container is managed by Docker Compose." } })).toMatchObject({ canUpdate: false, updateReason: expect.stringMatching(/Compose/) }); });
  it("keeps Update enabled for eligible standalone containers across all four connection types", () => { const profiles: DockerConnectionProfile[] = [local, { ...local, connectionType: "docker-context", contextName: "desktop-linux", contextSnapshot: { endpointType: "unix-socket", supported: true, importedAt: "x", lastDiscoveredAt: "x", isCurrentWhenSaved: false } }, { ...local, connectionType: "ssh", sshHost: "host", sshPort: 22, sshUsername: "user", authentication: { type: "password" }, remoteSocketPath: "/var/run/docker.sock" }, { ...local, connectionType: "docker-tls", host: "host", port: 2376, serverName: "host", caCertificatePath: "ca", clientCertificatePath: "cert", clientKeyPath: "key", tlsSnapshot: { serverName: "host", importedAt: "x" } }]; profiles.forEach((profile) => expect(getContainerActionCapabilities({ managementEnabled: true, hostStatus: "online", connection: connectionCapabilities(profile), containerState: "running", updateEligibility: { eligible: true, imageReference: "ghost:5-alpine" } }).canUpdate).toBe(true)); });
});
