import { setIcon } from "obsidian";
import type DockerConnectorPlugin from "../main";
import type { DockerContainerSummary } from "../containers/ContainerModels";
import type { DockerHostSnapshot } from "../models/DockerConnectionProfile";
import { renderMetricCards } from "../ui/MetricCards";
import { DEFAULT_APPLICATION_FILTERS, type ApplicationFilters, type DockerApplicationSummary } from "./ApplicationModels";
import { applicationContainer, buildDockerApplications, filterDockerApplications, sortDockerApplications } from "./ApplicationSelectors";

/** Read-only Compose-label dashboard. Its DOM is deliberately structured into stable card sections for responsive layout. */
export class ApplicationsTab {
  readonly filters: ApplicationFilters = { ...DEFAULT_APPLICATION_FILTERS };
  private selected?: DockerApplicationSummary;
  private origin?: HTMLElement;
  private searchTimer?: number;
  private detailPanel?: HTMLElement;
  private detailScrollTop = 0;
  private resetDetailScroll = false;

  constructor(private readonly plugin: DockerConnectorPlugin, private readonly rerender: () => void, private readonly openContainer: (containerId: string) => void) {}
  dispose(): void { if (this.searchTimer) window.clearTimeout(this.searchTimer); }

  render(root: HTMLElement, selectedHostId: string): void {
    if (this.detailPanel && !this.resetDetailScroll) this.detailScrollTop = this.detailPanel.scrollTop;
    const profiles = selectedHostId === "all" ? this.plugin.settings.profiles : this.plugin.settings.profiles.filter((profile) => profile.id === selectedHostId);
    const snapshots = profiles.map((profile) => this.plugin.snapshots.get(profile.id)).filter((snapshot): snapshot is DockerHostSnapshot => Boolean(snapshot));
    const containers = snapshots.flatMap((snapshot) => snapshot.containers);
    const statuses = this.statuses(containers);
    const applications = buildDockerApplications(containers, statuses, snapshots.flatMap((snapshot) => snapshot.networks), snapshots.flatMap((snapshot) => snapshot.volumes));
    const results = sortDockerApplications(filterDockerApplications(applications, this.filters), this.filters.sort);
    if (this.selected && !applications.some((application) => application.profileId === this.selected!.profileId && application.projectName === this.selected!.projectName)) {
      this.selected = undefined;
      this.detailPanel = undefined;
      this.detailScrollTop = 0;
    }
    root.addClass("docker-connector__applications-tab");
    this.header(root, selectedHostId === "all" ? "All Docker hosts" : profiles[0]?.name ?? "Selected host", applications, results);
    this.metrics(root, applications);
    this.toolbar(root);
    this.results(root, applications, results, containers, snapshots);
  }

  private statuses(containers: DockerContainerSummary[]) { return new Map(containers.map((container) => [`${container.hostProfileId}:${container.id}`, this.plugin.containerImageUpdateStatus(container.hostProfileId, container.id)]).filter((entry): entry is [string, NonNullable<ReturnType<DockerConnectorPlugin["containerImageUpdateStatus"]>>] => Boolean(entry[1]))); }
  private header(root: HTMLElement, host: string, all: DockerApplicationSummary[], results: DockerApplicationSummary[]): void { const header = root.createDiv({ cls: "dc-container-header" }); const copy = header.createDiv(); copy.createEl("h1", { text: "Applications" }); copy.createDiv({ text: `${results.length}${results.length === all.length ? "" : ` of ${all.length}`} ${pluralize(all.length, "application")}`, cls: "dc-container-result-count", attr: { "aria-live": "polite" } }); copy.createSpan({ text: host, cls: "docker-connector__muted" }); }
  private metrics(root: HTMLElement, all: DockerApplicationSummary[]): void { const running = all.filter((app) => app.runningCount > 0).length, degraded = all.filter((app) => app.status === "degraded").length, updates = all.filter((app) => app.updateAvailableCount > 0).length; renderMetricCards(root, [{ label: "Applications", value: all.length, detail: "Compose projects", icon: "boxes", active: !this.filters.updatesOnly, onClick: () => { this.filters.updatesOnly = false; this.rerender(); } }, { label: "Running", value: running, detail: "At least one container running", icon: "circle-play", tone: "success" }, { label: "Degraded", value: degraded, detail: degraded ? "Needs attention" : "No degraded applications", icon: "triangle-alert", tone: degraded ? "warning" : "muted", active: this.filters.status === "degraded", onClick: () => { this.filters.status = this.filters.status === "degraded" ? "all" : "degraded"; this.rerender(); } }, { label: "Updates available", value: updates, detail: updates ? "Applications with newer images" : "Everything is up to date", icon: "arrow-up-circle", tone: updates ? "warning" : "muted", active: this.filters.updatesOnly, ariaLabel: "Show only applications with image updates available", onClick: () => { this.filters.updatesOnly = !this.filters.updatesOnly; this.rerender(); } }], "Application summary"); }
  private toolbar(root: HTMLElement): void { const toolbar = root.createDiv({ cls: "dc-container-toolbar docker-connector__applications-toolbar" }); const search = toolbar.createDiv({ cls: "dc-container-search" }); setIcon(search.createSpan(), "search"); const input = search.createEl("input", { type: "search", value: this.filters.search, placeholder: "Search applications…", attr: { "aria-label": "Search applications" } }); input.oninput = () => { if (this.searchTimer) window.clearTimeout(this.searchTimer); this.searchTimer = window.setTimeout(() => { this.filters.search = input.value; this.rerender(); }, 180); }; this.select(toolbar, "Status", this.filters.status, [["all", "All statuses"], ["healthy", "Healthy"], ["degraded", "Degraded"], ["mixed", "Mixed"], ["stopped", "Stopped"]], (value) => { this.filters.status = value as ApplicationFilters["status"]; this.rerender(); }); this.select(toolbar, "Updates", this.filters.updatesOnly ? "available" : "all", [["all", "All"], ["available", "Updates available"]], (value) => { this.filters.updatesOnly = value === "available"; this.rerender(); }); this.select(toolbar, "Sort", this.filters.sort, [["name-asc", "Name A–Z"], ["name-desc", "Name Z–A"], ["container-count", "Container count"], ["updates", "Updates available"], ["status", "Status"]], (value) => { this.filters.sort = value as ApplicationFilters["sort"]; this.rerender(); }); }
  private results(root: HTMLElement, all: DockerApplicationSummary[], results: DockerApplicationSummary[], containers: DockerContainerSummary[], snapshots: DockerHostSnapshot[]): void { const panel = root.createDiv({ cls: "docker-connector__applications-results" }); if (!all.length) return this.empty(panel, "No Docker Compose applications found", "Containers managed outside Docker Compose remain available in the Containers view."); if (!results.length) return this.empty(panel, this.filters.updatesOnly ? "No applications currently have image updates available." : "No applications match the current filters.", undefined, () => { Object.assign(this.filters, DEFAULT_APPLICATION_FILTERS); this.rerender(); }); const layout = panel.createDiv({ cls: `docker-connector__applications-layout${this.selected ? " is-detail-open" : ""}` }); const list = layout.createDiv({ cls: "docker-connector__applications-list", attr: { "aria-label": "Docker Compose applications" } }); results.forEach((application) => this.card(list, application)); if (this.selected) this.detail(layout, this.selected, containers, snapshots); }
  private card(root: HTMLElement, application: DockerApplicationSummary): void { const selected = this.selected?.profileId === application.profileId && this.selected.projectName === application.projectName; const card = root.createEl("button", { cls: `docker-connector__application-card${selected ? " is-selected" : ""}`, attr: { "aria-label": `${application.projectName}, ${application.status}, ${pluralize(application.containerCount, "container")}`, "aria-pressed": String(selected) } }); card.onclick = () => { const changed = this.selected?.profileId !== application.profileId || this.selected.projectName !== application.projectName; this.selected = application; this.origin = card; this.resetDetailScroll ||= changed; this.rerender(); }; const header = card.createDiv({ cls: "docker-connector__application-card-header" }); header.createEl("strong", { text: application.displayName, attr: { title: application.displayName } }); header.createSpan({ text: application.status, cls: `dc-container-badge is-${application.status}` }); const summary = card.createDiv({ cls: "docker-connector__application-summary" }); summary.createSpan({ text: `${pluralize(application.serviceCount, "service")} · ${pluralize(application.containerCount, "container")} · ${application.runningCount} running${application.stoppedCount ? ` · ${application.stoppedCount} stopped` : ""}` }); if (application.updateAvailableCount) summary.createSpan({ text: `Updates available: ${application.updateAvailableCount}`, cls: "docker-connector__application-updates" }); const services = card.createDiv({ cls: "docker-connector__application-services" }); services.createSpan({ text: "Services", cls: "docker-connector__application-section-label" }); const chips = services.createDiv({ cls: "docker-connector__application-service-chips" }); application.services.slice(0, 5).forEach((service) => chips.createSpan({ text: service.serviceName, attr: { title: service.serviceName } })); if (application.services.length > 5) chips.createSpan({ text: `+${application.services.length - 5} more`, cls: "is-more" }); const footer = card.createDiv({ cls: "docker-connector__application-footer" }); footer.createSpan({ text: `${pluralize(application.networkNames.length, "network")} · ${pluralize(application.volumeNames.length, "volume")} · ${pluralize(application.imageReferences.length, "image")}` }); }
  private detail(root: HTMLElement, application: DockerApplicationSummary, containers: DockerContainerSummary[], snapshots: DockerHostSnapshot[]): void {
    const panel = root.createEl("aside", { cls: "dc-container-detail-panel docker-connector__application-detail", attr: { "aria-label": `Details for ${application.projectName}`, tabindex: "-1" } });
    this.detailPanel = panel;
    panel.scrollTop = this.resetDetailScroll ? 0 : this.detailScrollTop;
    this.detailScrollTop = panel.scrollTop;
    this.resetDetailScroll = false;
    const head = panel.createDiv({ cls: "dc-container-detail-header" }); const copy = head.createDiv(); copy.createEl("h2", { text: application.projectName }); copy.createSpan({ text: "Docker Compose application", cls: "docker-connector__muted" }); head.createSpan({ text: application.status, cls: `dc-container-badge is-${application.status}` }); const close = head.createEl("button", { attr: { "aria-label": "Close application details", title: "Close details" } }); setIcon(close, "x"); close.onclick = () => { this.selected = undefined; this.detailPanel = undefined; this.detailScrollTop = 0; this.rerender(); this.origin?.focus(); };
    const items = containers.filter((container) => application.containerIds.includes(container.id)), statuses = this.statuses(items);
    const snapshotRefresh = snapshots.find((snapshot) => snapshot.hostId === application.profileId)?.refreshedAt;
    this.section(panel, "Overview", [["Project", application.projectName], ["Status", application.status], ["Services", String(application.serviceCount)], ["Containers", String(application.containerCount)], ["Running", String(application.runningCount)], ["Stopped", String(application.stoppedCount)], ["Healthy", String(application.healthyCount)], ["Unhealthy", String(application.unhealthyCount)], ["Updates available", String(application.updateAvailableCount)], ["Last snapshot refresh", formatTimestamp(snapshotRefresh)]], "overview");
    const services = this.details(panel, "Services"); application.services.forEach((service) => { const row = services.createDiv({ cls: "docker-connector__application-service-row" }); row.createEl("strong", { text: service.serviceName, attr: { title: service.serviceName } }); row.createSpan({ text: `${pluralize(service.containerCount, "container")} · ${service.runningCount} running${service.unhealthyCount ? ` · ${service.unhealthyCount} unhealthy` : ""}` }); const images = service.imageReferences.join(", "); row.createSpan({ text: images, attr: { title: images } }); });
    const containerSection = this.details(panel, "Containers"); items.forEach((container) => { const item = applicationContainer(container, statuses); const button = containerSection.createEl("button", { cls: "docker-connector__application-container-row", attr: { "aria-label": `Open ${item.displayName} in Containers` } }); const main = button.createDiv({ cls: "docker-connector__application-container-main" }); main.createEl("strong", { text: item.displayName, attr: { title: item.displayName } }); const badges = main.createDiv({ cls: "docker-connector__application-container-badges" }); badges.createSpan({ text: displayState(item.state), cls: `dc-container-badge is-${item.state}` }); badges.createSpan({ text: displayHealth(item.health), cls: `dc-container-badge is-${item.health}` }); const metadata = [`Service: ${item.serviceName}`]; if (item.oneOff) metadata.push("One-off"); if (item.updateAvailable) metadata.push("Update available"); button.createDiv({ text: metadata.join(" · "), cls: "docker-connector__application-container-meta" }); button.onclick = () => this.openContainer(item.id); });
    const images = this.details(panel, "Images"); application.imageReferences.forEach((image) => { const count = items.filter((item) => item.image === image).length; const updates = items.filter((item) => item.image === image && statuses.get(`${item.hostProfileId}:${item.id}`)?.state === "available").length; const row = images.createDiv({ cls: "docker-connector__application-image-row" }); row.createSpan({ text: image, cls: "docker-connector__application-image-reference", attr: { title: image } }); row.createSpan({ text: `${pluralize(count, "container")} · ${pluralize(updates, "update")}`, cls: "docker-connector__application-image-counts" }); });
    this.section(panel, "Networking", application.networkNames.map((name) => [name, `${pluralize(items.filter((item) => item.networks.some((network) => network.name === name)).length, "attached container")}`]), "networking");
    this.section(panel, "Storage", [...application.volumeNames.map((name) => [name, pluralize(items.filter((item) => item.mounts.some((mount) => mount.name === name)).length, "attached container")] as [string, string]), ["Bind mounts", pluralize(items.flatMap((item) => item.mounts).filter((mount) => mount.type === "bind").length, "bind mount")]], "storage");
    this.section(panel, "Compose metadata", [["Project", application.projectName], ["Compose version", application.composeVersion], ["Working directory", shortPath(application.workingDirectory)], ["Config files", application.configFiles?.map(shortPath).join(", ")]], "metadata");
    panel.createDiv({ text: application.updateAvailableCount ? "Updates are informational. Update these services through Docker Compose." : "Application operations are read-only.", cls: "docker-connector__muted docker-connector__application-detail-note" });
  }
  private details(panel: HTMLElement, title: string): HTMLDetailsElement { const section = panel.createEl("details", { cls: "dc-container-detail-section", attr: { open: "" } }) as HTMLDetailsElement; section.createEl("summary", { text: title }); return section; }
  private section(panel: HTMLElement, title: string, rows: Array<[string, string | undefined]>, sectionClass?: string): void { const section = this.details(panel, title); if (sectionClass) section.addClass(`docker-connector__application-${sectionClass}-section`); rows.filter((row): row is [string, string] => Boolean(row[1])).forEach(([label, value]) => { const row = section.createDiv({ cls: "dc-container-detail-row" }); row.createSpan({ text: label, attr: { title: label } }); row.createSpan({ text: value, attr: { title: value } }); }); }
  private empty(root: HTMLElement, message: string, detail?: string, showAll?: () => void): void { const empty = root.createDiv({ cls: "dc-container-empty" }); empty.createSpan({ text: message }); if (detail) empty.createSpan({ text: detail, cls: "docker-connector__muted" }); if (showAll) { const button = empty.createEl("button", { text: "Show all applications" }); button.onclick = showAll; } }
  private select(root: HTMLElement, label: string, value: string, options: Array<[string, string]>, onChange: (value: string) => void): void { const control = root.createEl("label", { cls: "dc-container-select" }); control.createSpan({ text: label }); const select = control.createEl("select", { attr: { "aria-label": `Application ${label}` } }); options.forEach(([id, text]) => select.createEl("option", { value: id, text })); select.value = value; select.onchange = () => onChange(select.value); }
}

function pluralize(count: number, singular: string, plural = `${singular}s`): string { return `${count} ${count === 1 ? singular : plural}`; }
function displayState(state: string): string { return state.replace(/(^|[-_\s])(\w)/g, (_match, prefix: string, character: string) => `${prefix}${character.toUpperCase()}`); }
function displayHealth(health: string): string { return health === "none" ? "No health check" : displayState(health); }
function formatTimestamp(value: string | undefined): string | undefined { if (!value) return undefined; const timestamp = Date.parse(value); if (Number.isNaN(timestamp)) return value; const seconds = Math.max(0, Math.round((Date.now() - timestamp) / 1000)); if (seconds < 60) return "Just now"; if (seconds < 3600) return `${Math.floor(seconds / 60)} minutes ago`; if (seconds < 86400) return `${Math.floor(seconds / 3600)} hours ago`; return new Date(timestamp).toLocaleString(); }
function shortPath(value: string | undefined): string | undefined { if (!value) return undefined; const parts = value.replace(/\\/g, "/").split("/").filter(Boolean); return parts.length > 2 ? `…/${parts.slice(-2).join("/")}` : value; }
