import type { DockerContainerSummary } from "../containers/ContainerModels";
import type { DockerImageDetails, DockerImageSummary } from "./ImageModels";
type R = Record<string, unknown>; const obj = (v: unknown): R => v && typeof v === "object" && !Array.isArray(v) ? v as R : {}; const str = (v: unknown) => typeof v === "string" && v ? v : undefined; const num = (v: unknown) => typeof v === "number" && Number.isFinite(v) ? v : undefined;
/** Defensive Docker image response mapper. */
export class ImageMapper {
  /**
   * Docker's image list reports Containers as -1 unless the daemon was asked
   * to compute usage, so the host snapshot's containers are the authoritative
   * source. Callers without a snapshot omit them and keep Docker's value.
   */
  static summary(raw: unknown, hostProfileId: string, containers?: DockerContainerSummary[]): DockerImageSummary { const x = obj(raw); const warnings: string[] = []; const tags = strings(x.RepoTags); const digests = strings(x.RepoDigests); const first = tags[0] ?? "<none>:<none>"; const split = first.lastIndexOf(":"); const repository = split > 0 ? first.slice(0, split) : first === "<none>:<none>" ? "<none>" : first; const tag = split > 0 ? first.slice(split + 1) : "<none>"; const id = str(x.Id) ?? ""; const created = num(x.Created) ?? 0; const size = num(x.Size) ?? 0; if (!id) warnings.push("Image ID was missing."); if (!created) warnings.push("Image creation time was unavailable."); const references = containers?.filter((container) => container.imageId && sameImage(container.imageId, id)).map((container) => ({ id: container.id, name: container.displayName, state: container.state, health: container.health })) ?? []; return { id, shortId: id.replace(/^sha256:/, "").slice(0, 12) || "Unknown ID", repository, tag, repositoryTags: tags, repositoryDigests: digests, createdAt: created ? new Date(created * 1000).toISOString() : "", createdTimestamp: created, sizeBytes: size, sharedSizeBytes: num(x.SharedSize), virtualSizeBytes: num(x.VirtualSize), containersUsingImage: containers ? references.length : num(x.Containers) ?? 0, referencingContainers: references, dangling: tags.length === 0 || tags.every((tag) => tag === "<none>:<none>"), labels: labels(x.Labels), architecture: str(x.Architecture), operatingSystem: str(x.Os), hostProfileId, mapperWarnings: warnings }; }
  static details(raw: unknown, containers: DockerImageDetails["containersUsingImage"]): DockerImageDetails { const x = obj(raw); const config = obj(x.Config); return { id: str(x.Id) ?? "", parentId: str(x.Parent), createdAt: str(x.Created) ?? "", sizeBytes: num(x.Size) ?? 0, virtualSizeBytes: num(x.VirtualSize), sharedSizeBytes: num(x.SharedSize), architecture: str(x.Architecture), operatingSystem: str(x.Os), author: str(config.Author), comment: str(x.Comment), dockerVersion: str(x.DockerVersion), repositoryTags: strings(x.RepoTags), repositoryDigests: strings(x.RepoDigests), containersUsingImage: containers, labels: labels(config.Labels), mapperWarnings: [] }; }
}
/** Docker reports container image IDs with and without the digest prefix. */
function sameImage(containerImageId: string, imageId: string): boolean { const strip = (value: string) => value.replace(/^sha256:/, ""); return Boolean(imageId) && strip(containerImageId) === strip(imageId); }
function strings(value: unknown): string[] { return Array.isArray(value) ? value.filter((v): v is string => typeof v === "string") : []; } function labels(value: unknown): Record<string, string> { return Object.fromEntries(Object.entries(obj(value)).filter((e): e is [string, string] => typeof e[1] === "string")); }
