import type { DockerConnectionProfile, DockerContextEndpointType, SshAuthenticationConfig } from "../models/DockerConnectionProfile";
type LegacyHost = { id?: string; name?: string; description?: string; category?: string; endpoint?: string; createdAt?: string; };
/** Preserves legacy records as disabled SSH profiles for explicit user review. */
export function migrateLegacyHosts(input: unknown): DockerConnectionProfile[] {
  const hosts = (input as { hosts?: LegacyHost[] })?.hosts; if (!Array.isArray(hosts)) return [];
  return hosts.flatMap((host): DockerConnectionProfile[] => { if (!host.name) return []; const endpoint = host.endpoint?.trim(); if (!endpoint?.startsWith("ssh://")) return []; const parsed = new URL(endpoint); const now = new Date().toISOString(); return [{ id: host.id ?? crypto.randomUUID(), name: host.name, description: host.description, category: host.category, connectionType: "ssh", sshHost: parsed.hostname, sshPort: Number(parsed.port || 22), sshUsername: parsed.username || "", authentication: { type: "password" }, remoteSocketPath: "/var/run/docker.sock", enabled: false, createdAt: host.createdAt ?? now, updatedAt: now }]; });
}
/** Adds explicit non-secret authentication configuration to persisted SSH profiles. */
export function migrateProfiles(input: unknown): DockerConnectionProfile[] {
  const profiles = (input as { profiles?: Array<Record<string, unknown>> })?.profiles; if (!Array.isArray(profiles)) return migrateLegacyHosts(input);
  return profiles.flatMap((profile): DockerConnectionProfile[] => {
    if (profile.connectionType === "gateway" && typeof profile.name === "string" && typeof profile.gatewayUrl === "string") { const now = new Date().toISOString(); return [{ id: typeof profile.id === "string" ? profile.id : crypto.randomUUID(), name: profile.name, description: typeof profile.description === "string" ? profile.description : undefined, category: typeof profile.category === "string" ? profile.category : undefined, connectionType: "gateway", gatewayUrl: profile.gatewayUrl, gatewayName: typeof profile.gatewayName === "string" ? profile.gatewayName : undefined, enabled: profile.enabled !== false, createdAt: typeof profile.createdAt === "string" ? profile.createdAt : now, updatedAt: typeof profile.updatedAt === "string" ? profile.updatedAt : now }]; }
    if (profile.connectionType === "docker-tls" && typeof profile.name === "string" && typeof profile.host === "string" && typeof profile.port === "number" && typeof profile.serverName === "string" && typeof profile.caCertificatePath === "string" && typeof profile.clientCertificatePath === "string" && typeof profile.clientKeyPath === "string" && profile.tlsSnapshot && typeof profile.tlsSnapshot === "object") { const snapshot = profile.tlsSnapshot as Record<string, unknown>; const now = new Date().toISOString(); return [{ id: typeof profile.id === "string" ? profile.id : crypto.randomUUID(), name: profile.name, description: typeof profile.description === "string" ? profile.description : undefined, category: typeof profile.category === "string" ? profile.category : undefined, connectionType: "docker-tls", host: profile.host, port: profile.port, serverName: profile.serverName, caCertificatePath: profile.caCertificatePath, clientCertificatePath: profile.clientCertificatePath, clientKeyPath: profile.clientKeyPath, tlsSnapshot: { caCertificateFingerprint: typeof snapshot.caCertificateFingerprint === "string" ? snapshot.caCertificateFingerprint : undefined, clientCertificateFingerprint: typeof snapshot.clientCertificateFingerprint === "string" ? snapshot.clientCertificateFingerprint : undefined, clientCertificateSubject: typeof snapshot.clientCertificateSubject === "string" ? snapshot.clientCertificateSubject : undefined, clientCertificateIssuer: typeof snapshot.clientCertificateIssuer === "string" ? snapshot.clientCertificateIssuer : undefined, clientCertificateValidFrom: typeof snapshot.clientCertificateValidFrom === "string" ? snapshot.clientCertificateValidFrom : undefined, clientCertificateValidTo: typeof snapshot.clientCertificateValidTo === "string" ? snapshot.clientCertificateValidTo : undefined, serverName: profile.serverName, importedAt: typeof snapshot.importedAt === "string" ? snapshot.importedAt : now, lastValidatedAt: typeof snapshot.lastValidatedAt === "string" ? snapshot.lastValidatedAt : undefined }, enabled: profile.enabled !== false, createdAt: typeof profile.createdAt === "string" ? profile.createdAt : now, updatedAt: typeof profile.updatedAt === "string" ? profile.updatedAt : now }]; }
    if (profile.connectionType === "docker-context" && typeof profile.name === "string" && typeof profile.contextName === "string" && profile.contextSnapshot && typeof profile.contextSnapshot === "object") { const snapshot = profile.contextSnapshot as Record<string, unknown>; const type = snapshot.endpointType; if (!isContextEndpointType(type)) return []; const now = new Date().toISOString(); return [{ id: typeof profile.id === "string" ? profile.id : crypto.randomUUID(), name: profile.name, description: typeof profile.description === "string" ? profile.description : undefined, category: typeof profile.category === "string" ? profile.category : undefined, connectionType: "docker-context", contextName: profile.contextName, contextSnapshot: { description: typeof snapshot.description === "string" ? snapshot.description : undefined, isCurrentWhenSaved: snapshot.isCurrentWhenSaved === true, endpointType: type, endpointDisplay: typeof snapshot.endpointDisplay === "string" ? snapshot.endpointDisplay : undefined, skipTlsVerify: snapshot.skipTlsVerify === true, supported: snapshot.supported === true && type !== "tcp-insecure" && type !== "unknown", importedAt: typeof snapshot.importedAt === "string" ? snapshot.importedAt : now, lastDiscoveredAt: typeof snapshot.lastDiscoveredAt === "string" ? snapshot.lastDiscoveredAt : now }, enabled: profile.enabled !== false, createdAt: typeof profile.createdAt === "string" ? profile.createdAt : now, updatedAt: typeof profile.updatedAt === "string" ? profile.updatedAt : now }]; }
    if (profile.connectionType === "local" && profile.localEndpoint && typeof profile.name === "string") { const endpoint = profile.localEndpoint as { type?: unknown; socketPath?: unknown; pipePath?: unknown }; const valid = endpoint.type === "unix-socket" && typeof endpoint.socketPath === "string" ? { type: "unix-socket" as const, socketPath: endpoint.socketPath } : endpoint.type === "windows-named-pipe" && typeof endpoint.pipePath === "string" ? { type: "windows-named-pipe" as const, pipePath: endpoint.pipePath } : undefined; if (!valid) return []; const now = new Date().toISOString(); return [{ id: typeof profile.id === "string" ? profile.id : crypto.randomUUID(), name: profile.name, description: typeof profile.description === "string" ? profile.description : undefined, category: typeof profile.category === "string" ? profile.category : undefined, connectionType: "local", localEndpoint: valid, enabled: profile.enabled !== false, createdAt: typeof profile.createdAt === "string" ? profile.createdAt : now, updatedAt: typeof profile.updatedAt === "string" ? profile.updatedAt : now }]; }
    const host = typeof profile.sshHost === "string" ? profile.sshHost.trim() : ""; const username = typeof profile.sshUsername === "string" ? profile.sshUsername.trim() : ""; const name = typeof profile.name === "string" ? profile.name : "";
    if (!host || !username || !name) return [];
    const now = new Date().toISOString(); return [{ id: typeof profile.id === "string" ? profile.id : crypto.randomUUID(), name, description: typeof profile.description === "string" ? profile.description : undefined, category: typeof profile.category === "string" ? profile.category : undefined, connectionType: "ssh", sshHost: host, sshPort: Number(profile.sshPort) || 22, sshUsername: username, authentication: migrateAuthentication(profile.authentication), remoteSocketPath: typeof profile.remoteSocketPath === "string" ? profile.remoteSocketPath : "/var/run/docker.sock", hostKeyFingerprint: typeof profile.hostKeyFingerprint === "string" ? profile.hostKeyFingerprint : undefined, enabled: profile.enabled !== false, createdAt: typeof profile.createdAt === "string" ? profile.createdAt : now, updatedAt: typeof profile.updatedAt === "string" ? profile.updatedAt : now }];
  });
}
function isContextEndpointType(value: unknown): value is DockerContextEndpointType { return typeof value === "string" && ["unix-socket", "windows-named-pipe", "ssh", "tcp-tls", "tcp-insecure", "unknown"].includes(value); }

function migrateAuthentication(value: unknown): SshAuthenticationConfig {
  if (value && typeof value === "object" && (value as { type?: unknown }).type === "private-key" && typeof (value as { privateKeyPath?: unknown }).privateKeyPath === "string") return { type: "private-key", privateKeyPath: (value as { privateKeyPath: string }).privateKeyPath };
  return { type: "password" };
}
