import { constants } from "node:fs";
import { access, readFile, stat } from "node:fs/promises";
import { X509Certificate, createHash, createPrivateKey, createPublicKey } from "node:crypto";
import { homedir } from "node:os";
import { normalize, resolve } from "node:path";
import * as net from "node:net";
import { DockerConnectionError } from "../connections/DockerTransport";
import type { DockerTlsProfile } from "../models/DockerConnectionProfile";
import { hasControlCharacter } from "../utils/text";

/**
 * Non-secret certificate facts safe to retain in a profile. PEM contents and
 * TLS private-key passphrases are deliberately absent from this result.
 */
export interface DockerTlsLocalValidationResult { caCertificateFingerprint: string; clientCertificateFingerprint: string; clientCertificateSubject: string; clientCertificateIssuer: string; clientCertificateValidFrom: string; clientCertificateValidTo: string; }
export function validateDockerTlsHost(host: string): string { const value = host.trim(); if (!value) throw tls("DOCKER_TLS_HOST_REQUIRED", "Docker host is required."); if (value.length > 255 || hasControlCharacter(value) || /:\/\/|[/?#@]/.test(value) || (!net.isIP(value) && !/^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/.test(value))) throw tls("DOCKER_TLS_HOST_INVALID", "Docker host must be a DNS name or IP address without a URL scheme or credentials."); return value; }
export function validateDockerTlsPort(value: number): number { if (!Number.isFinite(value)) throw tls("DOCKER_TLS_PORT_REQUIRED", "Docker TLS port is required."); if (!Number.isInteger(value) || value < 1 || value > 65535) throw tls("DOCKER_TLS_PORT_INVALID", "Docker TLS port must be an integer from 1 to 65535."); return value; }
export function validateDockerTlsServerName(value: string): string { const name = value.trim(); if (!name) throw tls("DOCKER_TLS_SERVER_NAME_REQUIRED", "Server name is required."); if (name.length > 255 || hasControlCharacter(name) || /:\/\/|[/?#@]/.test(name)) throw tls("DOCKER_TLS_SERVER_NAME_INVALID", "Server name must not include a scheme, path, or credentials."); return name; }
export async function validateDockerTlsFiles(input: { caCertificatePath: string; clientCertificatePath: string; clientKeyPath: string; clientKeyPassphrase?: string }): Promise<DockerTlsLocalValidationResult> { const ca = await certificate(input.caCertificatePath, "CA"); const client = await certificate(input.clientCertificatePath, "CLIENT_CERT"); const key = await keyFile(input.clientKeyPath, input.clientKeyPassphrase); try { if (!createPublicKey(key).export({ type: "spki", format: "der" }).equals(client.publicKey.export({ type: "spki", format: "der" }) as Buffer)) throw tls("DOCKER_TLS_CERT_KEY_MISMATCH", "The selected client certificate and private key do not form a matching pair."); } finally { key.fill(0); } const now = Date.now(); if (Date.parse(client.validTo) < now) throw tls("DOCKER_TLS_CLIENT_CERT_EXPIRED", "The selected client certificate has expired."); if (Date.parse(client.validFrom) > now) throw tls("DOCKER_TLS_CLIENT_CERT_NOT_YET_VALID", "The selected client certificate is not yet valid."); return { caCertificateFingerprint: fingerprint(ca), clientCertificateFingerprint: fingerprint(client), clientCertificateSubject: client.subject, clientCertificateIssuer: client.issuer, clientCertificateValidFrom: new Date(client.validFrom).toISOString(), clientCertificateValidTo: new Date(client.validTo).toISOString() }; }
export function createDockerTlsProfile(input: { id: string; name: string; description?: string; category?: string; host: string; port: number; serverName: string; caCertificatePath: string; clientCertificatePath: string; clientKeyPath: string; validation: DockerTlsLocalValidationResult; now: string; existing?: DockerTlsProfile }): DockerTlsProfile { const host = validateDockerTlsHost(input.host), port = validateDockerTlsPort(input.port), serverName = validateDockerTlsServerName(input.serverName); return { id: input.existing?.id ?? input.id, name: input.name.trim(), description: input.description?.trim() || undefined, category: input.category?.trim() || undefined, connectionType: "docker-tls", host, port, serverName, caCertificatePath: resolveTlsPath(input.caCertificatePath), clientCertificatePath: resolveTlsPath(input.clientCertificatePath), clientKeyPath: resolveTlsPath(input.clientKeyPath), tlsSnapshot: { ...input.validation, serverName, importedAt: input.existing?.tlsSnapshot.importedAt ?? input.now, lastValidatedAt: input.now }, enabled: input.existing?.enabled ?? true, createdAt: input.existing?.createdAt ?? input.now, updatedAt: input.now }; }
function resolveTlsPath(value: string): string { const trimmed = value.trim(); const expanded = trimmed === "~" ? homedir() : trimmed.startsWith("~/") || trimmed.startsWith("~\\") ? `${homedir()}${trimmed.slice(1)}` : trimmed; return normalize(resolve(expanded)); }
async function file(path: string, prefix: string): Promise<Buffer> { if (!path.trim()) throw tls(`DOCKER_TLS_${prefix}_REQUIRED`, `Choose a ${prefix === "CA" ? "CA certificate" : prefix === "CLIENT_CERT" ? "client certificate" : "client private key"} file.`); const resolved = resolveTlsPath(path); let info; try { info = await stat(resolved); } catch { throw tls(`DOCKER_TLS_${prefix}_NOT_FOUND`, "The selected TLS file was not found."); } if (!info.isFile()) throw tls(`DOCKER_TLS_${prefix}_NOT_A_FILE`, "The selected TLS path is not a file."); try { await access(resolved, constants.R_OK); } catch { throw tls(`DOCKER_TLS_${prefix}_UNREADABLE`, "The selected TLS file cannot be read."); } const contents = await readFile(resolved); if (!contents.length) throw tls(`DOCKER_TLS_${prefix}_EMPTY`, "The selected TLS file is empty."); return contents; }
async function certificate(path: string, prefix: "CA" | "CLIENT_CERT"): Promise<X509Certificate> { const contents = await file(path, prefix); try { return new X509Certificate(contents); } catch { throw tls(`DOCKER_TLS_${prefix}_INVALID`, "The selected certificate is not a valid PEM certificate."); } finally { contents.fill(0); } }
async function keyFile(path: string, passphrase: string | undefined): Promise<Buffer> { const contents = await file(path, "CLIENT_KEY"); try { createPrivateKey({ key: contents, format: "pem", passphrase }); return contents; } catch (error) { contents.fill(0); const message = error instanceof Error ? error.message : ""; throw tls(/passphrase|decrypt/i.test(message) ? passphrase === undefined ? "DOCKER_TLS_CLIENT_KEY_PASSPHRASE_REQUIRED" : "DOCKER_TLS_CLIENT_KEY_PASSPHRASE_REJECTED" : "DOCKER_TLS_CLIENT_KEY_INVALID", "The selected client private key could not be parsed."); } }
function fingerprint(cert: X509Certificate): string { return createHash("sha256").update(cert.raw).digest("hex"); }
function tls(code: string, message: string): DockerConnectionError { return new DockerConnectionError(code, message); }
